- pom.xml
Received alerts through GitHub about a potential security vulnerability in our code repository in the version of io.vertx:vertx-core and io-vertx:vertx-web. 
Upgrade version as suggested to 3.5.4
> Update pom.xml to use latest version of io.vertx 

- descriptors/ModuleDescriptor-template.json
- pom.xml
- ramls/eholdings.raml
- src/main/java/org/folio/config/RMAPIConfiguration.java
- src/main/java/org/folio/config/RMAPIConfigurationClient.java
- src/main/java/org/folio/http/ConfigurationClientProvider.java
- src/main/java/org/folio/rest/converter/RMAPIConfigurationConverter.java
- src/main/java/org/folio/rest/impl/EholdingsConfigurationImpl.java
- src/main/java/org/folio/rest/util/HeaderConstants.java
- src/main/java/org/folio/rest/validator/HeaderValidator.java
- src/test/java/org/folio/config/RMAPIConfigurationClientTest.java
- src/test/java/org/folio/rest/impl/EholdingsConfigurationTest.java
- src/test/resources/responses/get-configuration.json
Implement GET /eholdings/configuration endpoint
Used ruby mod-kb-ebsco as reference.
Adapted RMAPIConfiguration class from mod-codex-ekb module to get configuration from RMAPI.
Used Wiremock to implement tests simlar to tests from ruby module.
* We need to wait until [initial module setup PR](https://github.com/folio-org/mod-kb-ebsco-java/pull/12 ) is merged, before merging this PR. 
This PR is only for commit https://github.com/folio-org/mod-kb-ebsco-java/pull/13/commits/a5d661fd279d27b474bc5733f67366481bf021b8
* Ruby module returns several field that seem to be specific to jsonapi:
Response from ruby module
```json
{
"data": {
"id": "configuration",
"type": "configurations",
"attributes": {
"customerId": "apidvcorp",
"apiKey": "****************************************",
"rmapiBaseUrl": …
```
> MODKBEKBJ-40: GET /eholdings/configuration endpoint

- pom.xml
Purpose
GitHub alert about a potential security vulnerability in our code repository in the version of com.fasterxml.jackson.core:jackson-databind.
Approach
Upgrade pom.xml with version 2.8.11.1
> Update pom.xml to use latest jackson-databind version

- ramls/types/token.json
There is an issue with invalid unicode character contained inside token's helpText. The problem can only be observed on win machine, mac/linux doesn't have one.
Replace token's helpText with simple value
> replace token's helpText with simple value to resolve invalid unicode character issue

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/rest/converter/VendorConverter.java
- src/main/java/org/folio/rest/impl/EholdingsProvidersImpl.java
- src/main/java/org/folio/rmapi/RMAPIService.java
- src/main/java/org/folio/rmapi/model/Proxy.java
- src/main/java/org/folio/rmapi/model/Vendor.java
- src/main/java/org/folio/rmapi/model/VendorById.java
- src/main/java/org/folio/rmapi/model/VendorToken.java
- src/test/java/org/folio/rest/impl/EholdingsProvidersImplTest.java
- src/test/java/org/folio/util/TestUtil.java
- src/test/resources/responses/rmapi/vendors/get-vendor-by-id-response.json
- src/test/resources/responses/rmapi/vendors/get-vendors-response.json
Per https://issues.folio.org/browse/MODKBEKBJ-19 we want to have the ability to get provider by id by supporting '/eholdings/providers/{provider_id}' endpoint
_How does this change fulfill the purpose?_
* Implement get providers by id method.
* Map vendor returned from RM API to a single Provider
* Add permissions to the request
> MODKBEKBJ-19 - Implement GET /eholdings/providers/{provider_id}

- src/main/java/org/folio/config/RMAPIConfigurationServiceCache.java
- src/main/java/org/folio/config/RMAPIConfigurationServiceImpl.java
- src/main/java/org/folio/rest/converter/RMAPIConfigurationConverter.java
- src/main/resources/application.properties
- src/test/java/org/folio/rest/impl/EholdingsProvidersImplTest.java
- src/test/java/org/folio/rest/impl/EholdingsStatusTest.java
- src/test/java/org/folio/util/TestUtil.java
- src/test/resources/responses/configuration/get-configuration-empty.json
Per https://issues.folio.org/browse/MODKBEKBJ-50 we need to change the behavior of backend validation if the configuration is not currently set up. 
For the situation when we do not have a configuration entity and perform 
`GET /status`
we recieve following response 
`Internal server error` with code 500
Added additional check for RMAPI configuration parameters.
This check will prevent retriving configuration details if configuration credentials are empty.
In case we do not have configuration and and perform 
`GET /status`
we will recieve 
`{
“data”: {
“id”: “status”,
“type”: “statuses”,
“attributes”: {
“isConfigurationValid”: false
}
},
“jsonapi”: {
“version”: “1.0”
}
}`
with response code 200 
there is the issue with maven-surface-plugin, which brokes Jenkins build and already reported …
> MODKBEKBJ-50 - Verify configuration setup

- src/main/java/org/folio/rest/validator/TitleParametersValidator.java
- src/test/java/org/folio/rest/validator/TitleParametersValidatorTest.java
https://github.com/folio-org/mod-kb-ebsco-java/pull/27 addressed most of the implementation of /eholdings/titles endpoint. While testing the endpoint, identified a couple of errors which could be handled better. Before this PR, code was passing through error messages from RM API whose terminology differs from this module's for certain terms. This PR adds additional validation before passing the request to RM API and gives specific error messages in terms of consumers of this API.
- Add a couple more validations of query params that can be added to this endpoint.
- Add specific error messages to be returned after validations.
- Add associated unit tests.
*Before*
*After*
> MODKBEKBJ-35: Update error handling for titles endpoint

- src/main/java/org/folio/rest/impl/EholdingsProvidersImpl.java
- src/main/java/org/folio/rmapi/RMAPIService.java
- src/test/java/org/folio/rest/impl/EholdingsProvidersImplTest.java
MODKBEKBJ-54
Add validation for providerId to make api tests pass
Parse providerId before sending request to RM API
It appears that "type: integer" is not supported for path parameters, so I had to parse providerId manually
> MODKBEKBJ-54: Validate that providerId is a number

- ramls/traits/sortable.raml
- src/main/java/org/folio/rest/impl/EholdingsProvidersImpl.java
- src/main/java/org/folio/rest/impl/EholdingsTitlesImpl.java
- src/main/java/org/folio/rest/validator/TitleParametersValidator.java
- src/main/java/org/folio/rmapi/builder/QueriableUrlBuilder.java
- src/test/java/org/folio/rest/validator/TitleParametersValidatorTest.java
- src/test/java/org/folio/rmapi/builder/QueriableUrlBuilderTest.java
- src/test/java/org/folio/rmapi/builder/TitlesFilterableUrlBuilderTest.java
Change default value of sort parameter to "relevance"
Made "relevance" to be default value for sort,
if search query is not specified then sort option is ignored and is treated
as "name"
> MODKBEKBJ-35: Make relevance default sort option

- descriptors/ModuleDescriptor-template.json
- ramls/types/publicationType.json
- ramls/types/titles/title.json
- ramls/types/titles/titleData.json
- ramls/types/titles/titleListDataAttributes.json
- src/main/java/org/folio/rest/converter/TitleConverter.java
- src/main/java/org/folio/rest/impl/EholdingsTitlesImpl.java
- src/main/java/org/folio/rmapi/RMAPIService.java
- src/test/java/org/folio/rest/impl/EholdingsTitlesTest.java
- src/test/resources/responses/rmapi/titles/get-title-by-id-not-found-response.json
- src/test/resources/responses/rmapi/titles/get-title-by-id-response.json
Per https://issues.folio.org/browse/MODKBEKBJ-37 implement titles get by id endpoint
- Added module descriptor permission, plus missing permission for provider put
- RAML Updates (moved publication types enum to common class to be shared by list and title details, udated title.json relationship to reflect resources only
- Added conversion of title detail record from RM API format to JSON API format
- Added unit tests with updated refactoring to use WireMockTestBase
https://issues.folio.org/browse/MODKBEKBJ-83
> MODKBEKBJ-37 - Implement Title Get By Id Endpoint

- src/main/java/org/folio/rest/converter/VendorConverter.java
- src/main/java/org/folio/rmapi/model/Vendor.java
- src/main/java/org/folio/rmapi/model/VendorById.java
- src/test/resources/responses/rmapi/vendors/get-vendor-by-id-response.json
- src/test/resources/responses/rmapi/vendors/get-vendors-response.json
Fix issue that occurs while parsing provider token.
- Change vendor token in vendor class to string
- Add object instance of vendor token to "VendorById" class
It appears that provider token might be an object or a string in some cases.
> MODKBEKBJ-52 - Fix provider token mapping issue

- src/main/java/org/folio/rmapi/RMAPIService.java
- src/test/java/org/folio/rest/impl/EholdingsProvidersImplTest.java
Error messages from RM API return messages containing `vendor` instead of `provider`. 
Mod-kb-ebsco currently updates message body and replaces Vendor, vendor with Provider, provider respectively in the following code:
https://github.com/folio-org/mod-kb-ebsco/blob/9b68934c587983e28cb7a3d9c73e7a562b31ac90/app/controllers/application_controller.rb#L99 
Update java module to do the same replacement
Update unit test to reflect vendor instead of provider
Before
After
> Update Provider Error Messages from RM API (vendor vs provider)

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/rest/converter/RootProxyConverter.java
- src/main/java/org/folio/rest/impl/EHoldingsRootProxyImpl.java
- src/main/java/org/folio/rest/validator/RootProxyPutBodyValidator.java
- src/main/java/org/folio/rmapi/RMAPIService.java
- src/test/java/org/folio/rest/impl/EHoldingsRootProxyImplTest.java
- src/test/java/org/folio/rest/validator/RootProxyPutBodyValidatorTest.java
- src/test/resources/requests/kb-ebsco/put-root-proxy.json
- src/test/resources/requests/rmapi/proxiescustomlabels/put-root-proxy-custom-labels.json
- src/test/resources/responses/rmapi/proxiescustomlabels/get-root-proxy-custom-labels-updated-response.json
- src/test/resources/responses/rmapi/proxiescustomlabels/put-root-proxy-custom-labels-400-error-response.json
Per https://issues.folio.org/browse/MODKBEKBJ-95, we are supposed to implement `PUT /eholdings/root-proxy`. This PR addresses that.
- Add support for updating root proxy by implementing PUT /eholdings/root-proxy
- Add associated unit tests
- Add associated permissions in module descriptor
> MODKBEKBJ-95: Implement PUT root proxy endpoint

- src/main/java/org/folio/rmapi/RMAPIService.java
- src/test/java/org/folio/rest/impl/EHoldingsRootProxyImplTest.java
- src/test/resources/requests/rmapi/proxiescustomlabels/put-root-proxy-custom-labels-without-empty-display-labels.json
- src/test/resources/responses/rmapi/proxiescustomlabels/get-root-proxy-custom-labels-with-empty-labels-success-response.json
During manual testing, identified an issue with the existing implementation of PUT /eholdings/root-proxy code.  Modify code accordingly to fix the issue. 
- RM API uses the same endpoint for a PUT request to /{custID} for updating both root proxies and custom labels
- We make a GET call to get root proxy and custom labels and update root proxy with the new one submitted by user, and we have to filter custom labels that we get to not contain any custom labels that have empty string for "displayLabel" because RM API gives a 400 Bad Request when we try to update custom labels with empty string.
- Filter out those custom labels that we get with empty display labels before making the PUT request to RM API to avoid the 400 from RM API
- Confirmed that Ruby code does the same.
- Add unit test
> Fix issue with PUT /eholdings/root-proxy

- descriptors/ModuleDescriptor-template.json
- ramls/types/publicationType.json
- ramls/types/resources/resourceDataAttributes.json
- src/main/java/org/folio/rest/converter/CommonAttributesConverter.java
- src/main/java/org/folio/rest/converter/ResourcesConverter.java
- src/main/java/org/folio/rest/converter/TitleConverter.java
- src/main/java/org/folio/rest/impl/EholdingsResourcesImpl.java
- src/main/java/org/folio/rest/model/ResourceId.java
- src/main/java/org/folio/rmapi/RMAPIService.java
- src/main/java/org/folio/rmapi/model/CustomerResources.java
- src/test/java/org/folio/rest/impl/EholdingsResourcesImplTest.java
- src/test/java/org/folio/rest/impl/EholdingsTitlesTest.java
- src/test/resources/responses/rmapi/resources/get-resource-by-id-not-found-response.json
- src/test/resources/responses/rmapi/resources/get-resource-by-id-success-response.json
Per https://issues.folio.org/browse/MODKBEKBJ-31, we are supposed to implement `GET /eholdings/resources/{resourceId}`. This PR addresses that.
- Implement `GET /eholdings/resources/{resourceId}`
- Add unit tests
> MODKBEKBJ-31: GET resource by resourceId

- lombok.config
- pom.xml
Configure test coverage
- add JaCoCo plugin to maven build
- enable it for test phase by applying test-coverage profile
- add Lombok configuration property `lombok.addLombokGeneratedAnnotation` to ignore generated classes during test coverage estimation
> MODKBEKBJ-105 tune up code coverage

- descriptors/ModuleDescriptor-template.json
- ramls/examples/providers/providers_providerId_packages_get_400_response.json
- ramls/examples/providers/providers_providerId_packages_get_404_response.json
- ramls/providers.raml
- src/main/java/org/folio/rest/impl/EholdingsProvidersImpl.java
- src/main/java/org/folio/rmapi/RMAPIService.java
- src/main/java/org/folio/rmapi/model/Vendor.java
- src/test/java/org/folio/rest/impl/EholdingsProvidersImplTest.java
- src/test/resources/responses/packages/get-packages-by-provider-id-response.json
Per https://issues.folio.org/browse/MODKBEKBJ-21 we want to have the ability to get packages by provider id by supporting  `/eholdings/providers/{provider_id}/packages` endpoint
- Implement get provider packages method
- Added permissions to the request
- Mapped packages returned from RM API by provider id to a collection of packages
> MODKBEKBJ-21 - Implement GET /eholdings/providers/{provider_id}/packages

- descriptors/ModuleDescriptor-template.json
- ramls/eholdings.raml
- src/main/java/org/folio/config/cache/RMAPIConfigurationCache.java
- src/main/java/org/folio/rest/impl/EholdingsCacheImpl.java
- src/test/java/org/folio/rest/impl/EholdingsCacheImplTest.java
- src/test/java/org/folio/rest/impl/WireMockTestBase.java
- src/test/java/org/folio/util/TestUtil.java
Implement endpoint to invalidate configuration cache
Added /eholdings/cache endpoint to eholdings.raml and to ModuleDescriptor-template.json
Implemented endpoint to only invalidate cache for current tenant
> MODKBEKBJ-103: Add an endpoint for invalidating configuration cache

- pom.xml
- src/main/java/org/folio/rmapi/RMAPIService.java
- src/main/resources/log4j.properties
- src/main/resources/log4j2.xml
- src/test/java/org/folio/rest/impl/WireMockTestBase.java
- src/test/resources/log4j.properties
- src/test/resources/log4j2-test.xml
Make log4j2 a logging implementation for the module
- add log4j2 configuration for tests (`log4j2-test.xml`) and primary code (`log4j2.xml`). the last one will be used only if `domain-models-runtime` doesn't provide the configuration
- remove explicit usage of slf4j logger from the tests; add log4j-slf4j bridge to be used by wiremock
- use log placeholders wherever an object has to be added into the log message 
- set log4j2 delegate factory for tests in `maven-surefire-plugin`
* `RestLancher` initialize vertx logging delegate factory in static block and it's log4j2 one
It'd be better to define the property in deployment descriptor or other configuration but that's we have for the moment.  
* `domain-models-runtime` jar contains log4j2.properties. it can be overridden only by setting …
> MODKBEKBJ-113 replace logging implementation with log4j2

- ramls/types/hasManyRelationship.json
- ramls/types/packages/package.json
- ramls/types/packages/packageRelationships.json
- src/main/java/org/folio/rest/converter/PackagesConverter.java
Change raml schema for implementation of MODKBEKBJ-62 and MODKBEKBJ-63
Added included attribute with type Object, so that it can include both
title and provider objects
Added hasManyRelationship.json and changed packageRelationships.json to
use it. Old metaIncluded.json schema doesn't have fields for id and type
of related objects.
> MODKBEKBJ-62: Change raml schema to have relationship and included attributes

- src/main/java/org/folio/config/RMAPIConfiguration.java
- src/main/java/org/folio/config/RMAPIConfigurationServiceCache.java
- src/main/java/org/folio/config/RMAPIConfigurationServiceImpl.java
- src/main/java/org/folio/config/api/RMAPIConfigurationService.java
- src/main/java/org/folio/config/cache/RMAPIConfigurationCache.java
- src/main/java/org/folio/rest/converter/RMAPIConfigurationConverter.java
- src/main/java/org/folio/rest/impl/EHoldingsRootProxyImpl.java
- src/main/java/org/folio/rest/impl/EholdingsCacheImpl.java
- src/main/java/org/folio/rest/impl/EholdingsConfigurationImpl.java
- src/main/java/org/folio/rest/impl/EholdingsPackagesImpl.java
- src/main/java/org/folio/rest/impl/EholdingsProvidersImpl.java
- src/main/java/org/folio/rest/impl/EholdingsProxyTypesImpl.java
- src/main/java/org/folio/rest/impl/EholdingsResourcesImpl.java
- src/main/java/org/folio/rest/impl/EholdingsStatusImpl.java
- src/main/java/org/folio/rest/impl/EholdingsTitlesImpl.java
- src/test/java/org/folio/rest/impl/WireMockTestBase.java
- src/test/java/org/folio/rmapi/config/RMAPIConfigurationServiceTest.java
Use the way to share data between verticles that is provided by Vert.x instead of relying on singleton with static variable
Made RMAPIConfiguration immutable and implemented cache by using
vertx SharedData object
> MODKBEKBJ-114: Change cache implementation to use vertx.sharedData

- src/main/java/org/folio/rest/converter/PackagesConverter.java
- src/main/java/org/folio/rest/converter/ResourcesConverter.java
- src/main/java/org/folio/rest/impl/EholdingsPackagesImpl.java
- src/main/java/org/folio/rest/util/RestConstants.java
- src/main/java/org/folio/rmapi/RMAPIService.java
- src/main/java/org/folio/rmapi/result/PackageResult.java
- src/test/java/org/folio/rest/impl/EholdingsPackagesTest.java
- src/test/java/org/folio/rest/impl/PackagesTestData.java
- src/test/resources/responses/kb-ebsco/packages/expected-package-by-id.json
Support '?include=resources' for /eholdings/packages/{packageId}
Retrieved resources by package id and added them to package response if
include flag is set to include=resources.
Moved package test fixture to json file, made other small test refactorings
> MODKBEKBJ-62: Support '?include=resources' for /eholdings/packages/{packageId}

- ramls/types/providers/providerPutData.json
- ramls/types/providers/providerPutRequest.json
- ramls/types/proxies/rootProxyPutData.json
- ramls/types/proxies/rootProxyPutRequest.json
Per https://issues.folio.org/browse/MODKBEKBJ-96 we want to fix API Tests for PUT /eholdings/root-proxy endpoint. In case "attributes" property is null mod-kb-ebsco-java returns 500 code, but mod-kb-ebsco returns 422. Also, in order to have same style for an error message if "attributes" is null we need to change response with error message for providers.
- made attributes and type required for proxies and providers like in cases with titles,packages,resources
> MODKBEKBJ-96 - Changes for API Tests PUT /eholdings/root-proxy endpoint

- src/main/java/org/folio/rest/validator/ResourcePutBodyValidator.java
- src/test/java/org/folio/rest/validator/ResourcePutBodyValidatorTest.java
Per https://issues.folio.org/browse/MODKBEKBJ-81 we want to have API Tests for PUT /eholdings/resources/{resourceId} endpoint, in order to fix some tests we need to add validation for "isSelected" property
- added validation for "isSelected" property if it's not specified in request's put body
> MODKBEKBJ-81 - API Tests PUT /eholdings/resources/{resourceId} endpoint

- descriptors/ModuleDescriptor-template.json
Per [MODKBEKBJ-154](https://issues.folio.org/browse/MODKBEKBJ-154) Refactor permission names to follow FOLIO permissions naming convention
Follow general guidelines from https://dev.folio.org/guidelines/naming-conventions/
and permission mapping from https://docs.google.com/spreadsheets/d/1IJnlWvi4k-wFatDNimx9fQ375evHSIIxtGMookHvs-I/edit#gid=214288204
> MODKBEKBJ-154 Refactor permission names to follow FOLIO permissions naming convention

- pom.xml
Set system property which is used by RAML generator to build a list of module's json schemas
RAML generator can build a list of json schemas defined in the module. The list is then retrieved from `/_/jsonSchemas` endpoint. There is a special system property `schema_paths` to be used for file filter configuration. In this PR the property is set to
`types/**`
Thus all json schemas contained inside `types` folder will be included in the list
> MODKBEKBJ-142 add schema path as a property to pom.xml

- Jenkinsfile
- NEWS.md
- pom.xml
Per https://issues.folio.org/browse/FOLIO-1753 we are releasing mod-kb-ebsco-java module so that it can be included in environments and we can start deprecating the use of mod-kb-ebsco (Ruby Version). Of note - the Ruby version will continue to be included as part of Q3 and Q4 releases. Of note -  The Java module provides eholdings interface version 1.0, the Ruby module provides eholdings interface version 0.1
- Update version, news and set publishModDescriptor = yes
- Used `mvn -DautoVersionSubmodules=true release:clean release:prepare` so to properly handle release and snapshot versioning
- Release was updated from 2.0.0 to 2.0.1 due to an sonar reported issue regarding commented code in pom -- resolved this and updated release version
Followed release procedures as noted at …
> FOLIO-1753 - Release 2.0.1

- pom.xml
updated RMB version
Per https://issues.folio.org/browse/MODKBEKBJ-155 we want to use the newest version of RMB to be able to get the list of JSON schemas available for mod-kb-ebsco-java module.
changed RMB version to latest 23.5.0
https://github.com/folio-org/raml-module-builder/releases/tag/v23.5.0
> MODKBEKBJ-155 - Refactor Postman API test

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/rest/impl/TenantApiImpl.java
- src/main/resources/templates/db_scripts/create-table.sql
- src/main/resources/templates/db_scripts/schema.json
- src/main/resources/templates/db_scripts/test-data.sql
Per https://issues.folio.org/browse/MODKBEKBJ-167 we want to be able to store tag data 
* added /_/tenant endpoint to ModuleDescriptor file because database schema creation triggers on the step of enabling the module to a tenant.
* created a schema to store tags
* added tested data
* Tenant Api - https://github.com/folio-org/raml-module-builder#tenant-api
* To enable test data creation we have to specify an environment variable called `test.mode` in DeploymentDescriptor.
the corresponding log file with message about test data creation can be viewed by 
`docker logs <docker_container_name>`
> MODKBEKBJ-167 - Create database script to store tag data

- src/main/java/org/folio/rest/impl/EholdingsProvidersImpl.java
- src/test/java/org/folio/rest/impl/EholdingsProvidersImplTest.java
- src/test/java/org/folio/rest/impl/WireMockTestBase.java
- src/test/resources/responses/kb-ebsco/providers/expected-provider-with-packages.json
- src/test/resources/responses/kb-ebsco/providers/expected-provider-with-updated-tags.json
- src/test/resources/responses/kb-ebsco/providers/expected-provider.json
- src/test/resources/responses/kb-ebsco/providers/expected-updated-provider.json
- src/test/resources/responses/rmapi/vendors/get-vendor-without-selected-packages-response.json
Make provider tags updateable when provider has no selected packages.
Don't send request to RM API when provider doesn't have selected packages.
Add unit, change provider tests to use json files
> MODKBEKBJ-182 Update tags for provider with 0 selected packages

- src/main/java/org/folio/rest/converter/resources/CommonResourceConverter.java
- src/test/java/org/folio/rest/converter/packages/PackageRequestConverterTest.java
- src/test/java/org/folio/rest/converter/packages/PackageResponseConverterTest.java
- src/test/java/org/folio/rest/converter/resources/ResourceRequestConverterTest.java
- src/test/resources/responses/rmapi/titles/get-custom-title-with-coverage-dates-asc.json
Due to  https://issues.folio.org/browse/MODKBEKBJ-194 coverage dates return to UI in asc order but should be in desc order.
* fixed for resource custom coverage to return dates in desc order
> MODKBEKBJ-194 - Custom Coverages are not returned in descending order

- src/main/java/org/folio/rest/impl/EholdingsPackagesImpl.java
- src/test/resources/requests/kb-ebsco/package/put-package-not-selected-non-empty-fields.json
PR https://github.com/folio-org/mod-kb-ebsco-java/pull/119 introduced bug, in which package can't be removed from holdings, because put request is not sent to RM API for unselected managed packages.
Fix this bug by sending request to RM API in case if it is a valid update that will unselect package
Add special case to condition that skips sending put request to RM API
> MODKBEKBJ-197 Fix removal of managed package from holdings

- src/main/java/org/folio/rest/impl/EholdingsResourcesImpl.java
- src/test/java/org/folio/rest/impl/EholdingsResourcesImplTest.java
PR https://github.com/folio-org/mod-kb-ebsco-java/pull/116 introduced bug, in which resource can't be removed from holdings, because put request is not sent to RM API for unselected not custom resource.
Fix this bug by sending request to RM API in case if it is a valid update that will unselect resource
Add special case to condition that skips sending put request to RM API
> MODKBEKBJ-183: Fix bug with removing selected resource from holdings

- pom.xml
Update version to V2.2.0 in prep for Q1 release
Version 2.1.0 release was closed (per below PR) so as to include some bug fixes
https://github.com/folio-org/mod-kb-ebsco-java/pull/126
Update release to v2.2.0 to avoid issues with any Jenkins remnants created related for v2.1.0
Below issues to be included in Q1 release
https://github.com/folio-org/mod-kb-ebsco-java/pull/127
https://github.com/folio-org/mod-kb-ebsco-java/pull/125
> Prep for release 2.2.0

- NEWS.md
- pom.xml
Create Q1 release which includes the following changes since v2.0.3
* https://issues.folio.org/browse/MODKBEKBJ-162- Tags: assign/unassign tags to Package record
* https://issues.folio.org/browse/MODKBEKBJ-163 - Tags: assign/unassign tags to Title record
* https://issues.folio.org/browse/MODKBEKBJ-165 - Tags: assign/unassign tags to Resource record
* https://issues.folio.org/browse/MODKBEKBJ-168 - Error when removing managed titles from holdings
* https://issues.folio.org/browse/MODKBEKBJ-174- Remove title from holdings - Error converting value \"Streaming Video\"
* https://issues.folio.org/browse/MODKBEKBJ-176 - Bug on adding resource to holdings
* https://issues.folio.org/browse/MODKBEKBJ-177- Add a method to modify title
* https://issues.folio.org/browse/MODKBEKBJ-198 - DB upgrade …
> Release 2.2.0

- descriptors/ModuleDescriptor-template.json
- pom.xml
Per https://issues.folio.org/browse/MODKBEKBJ-227 we want to explicitly declare a dependency of mod-configuration interface called `configuration` and version 2.0
* modified ModuleDescriptor requires section with mod-configuration interface
* removed mod-configuration-client dependency in pom file as it is provided by folio-holdingsiq-client library
> MODKBEKBJ-227 - Modify ModuleDescriptor

- src/main/java/org/folio/common/FutureUtils.java
- src/main/java/org/folio/rest/impl/EholdingsPackagesImpl.java
- src/test/java/org/folio/rest/impl/EholdingsPackagesTest.java
- src/test/resources/requests/kb-ebsco/package/put-package-custom-not-selected.json
Fix bug where package and tag data is not delete from local database if custom package is deleted on PUT request
If getting package after update results in ResourceNotFoundException, then remove tag and package information from database.
> Delete tags when custom package is deleted through PUT

- src/main/java/org/folio/repository/packages/PackageRepositoryImpl.java
- src/main/java/org/folio/repository/providers/ProviderRepositoryImpl.java
- src/main/java/org/folio/repository/resources/ResourceRepositoryImpl.java
- src/main/java/org/folio/repository/tag/TagRepositoryImpl.java
- src/main/java/org/folio/repository/titles/TitlesRepositoryImpl.java
- src/test/java/org/folio/repository/packages/PackageRepositoryImplTest.java
- src/test/java/org/folio/repository/providers/ProviderRepositoryImplTest.java
- src/test/java/org/folio/repository/resources/ResourcesRepositoryImplTest.java
- src/test/java/org/folio/repository/tag/TagRepositoryImplTest.java
- src/test/java/org/folio/repository/titles/TitleRepositoryImplTest.java
- src/test/java/org/folio/rest/impl/EholdingsPackagesTest.java
- src/test/java/org/folio/rest/impl/EholdingsProvidersImplTest.java
- src/test/resources/responses/rmapi/packages/get-packages-by-provider-id-empty.json
- src/test/resources/responses/rmapi/resources/get-resources-by-package-id-response-empty.json
Fix "Internal server error" in situations when list of results is empty,
currently in some situations Repository classes will try to construct SQL query using an empty list, and this leads to sql exception
Add checks for cases when repository receives an empty collection as a parameter
> MODKBEKBJ-271: Add check for empty collections in repositories

- ramls/types/packages/packagePostDataAttributes.json
- ramls/types/packages/packagePutData.json
- ramls/types/packages/packagePutDataAttributes.json
- src/main/java/org/folio/rest/converter/packages/PackageRequestConverter.java
- src/main/java/org/folio/rest/impl/EholdingsPackagesImpl.java
- src/main/java/org/folio/rest/validator/CustomPackagePutBodyValidator.java
- src/main/java/org/folio/rest/validator/PackagePutBodyValidator.java
- src/main/java/org/folio/rmapi/result/PackageResult.java
- src/test/java/org/folio/rest/converter/packages/PackageRequestConverterTest.java
- src/test/java/org/folio/rest/impl/EholdingsPackagesTest.java
- src/test/java/org/folio/rest/impl/PackagesTestData.java
- src/test/java/org/folio/rest/validator/CustomPackagePutBodyValidatorTest.java
- src/test/java/org/folio/rest/validator/PackagePutBodyValidatorTest.java
- src/test/resources/requests/kb-ebsco/package/post-package-request.json
- src/test/resources/requests/kb-ebsco/package/put-package-custom-multiple-attributes
- src/test/resources/requests/kb-ebsco/package/put-package-selected.json
updates for https://issues.folio.org/browse/MODKBEKBJ-283
After discussion with UI team decided not to remove "tags" from the schemas for POST and PUT package methods as those values for tags are used for the sequential call to update package tags.
* removed tags update for POST /packages
* removed tags update for PUT /packages/{id}
* updated/removed redundant tests
> MODKBEKBJ-283 - Remove update of package tags from package endpoints

- ramls/types/resources/resourcePutDataAttributes.json
- src/main/java/org/folio/rest/impl/EholdingsResourcesImpl.java
- src/main/java/org/folio/rmapi/result/ResourceResult.java
- src/test/java/org/folio/rest/impl/EholdingsResourcesImplTest.java
Remove code that updates tags https://issues.folio.org/browse/MODKBEKBJ-287
* removed tags update for PUT /resources/{id}
* updated/removed redundant tests
> MODKBEKBJ-287 Remove update of resource tags from resource endpoints

- src/main/java/org/folio/repository/holdings/LoadStatus.java
- src/test/java/org/folio/rest/impl/IntegrationTestSuite.java
- src/test/java/org/folio/rest/impl/LoadHoldingsImplTest.java
- src/test/java/org/folio/rest/impl/LoadServiceFacadeImplTest.java
- src/test/java/org/folio/rest/impl/WireMockTestBase.java
- src/test/resources/responses/rmapi/holdings/status/get-status-none.json
Jira: MODKBEKBJ-306
Correctly process "None" status on loading holdings
Add None status
Additionally:
Fix an issue in WireMockTestBase to make it use TestConfig
Fix an issue in LoadHoldingsImplTest where HOLDINGS_GET_ENDPOINT returned
an error instead of HOLDINGS_STATUS_ENDPOINT
> MODKBEKBJ-306: Correctly process "None" status on loading holdings

- src/main/java/org/folio/repository/holdings/status/HoldingsStatusTableConstants.java
- src/main/java/org/folio/rest/impl/TenantApiImpl.java
- src/main/resources/templates/db_scripts/create-holdings-status-table.sql
- src/main/resources/templates/db_scripts/schema.json
- src/test/java/org/folio/rest/impl/LoadHoldingsStatusImplTest.java
- src/test/java/org/folio/util/HoldingsStatusUtil.java
Don't override loading status when TenantAPI is called second time
Add unique column to holdings_status to ensure that only one row can be
inserted.
Change INSERT statement to do nothing if status already exists
> MODKBEKBJ-311: Don't override loading status when TenantAPI is called second time

- ramls/eholdings.raml
- ramls/types/loadHoldings/loadHoldingsStatusAttributes.json
- src/main/java/org/folio/common/VertxIdProvider.java
- src/main/java/org/folio/common/VertxIdService.java
- src/main/java/org/folio/repository/holdings/status/HoldingsLoadingStatusFactory.java
- src/main/java/org/folio/repository/holdings/status/HoldingsStatusRepositoryImpl.java
- src/main/java/org/folio/repository/holdings/status/HoldingsStatusTableConstants.java
- src/main/java/org/folio/rest/impl/LoadHoldingsImpl.java
- src/main/java/org/folio/service/holdings/HoldingsService.java
- src/main/java/org/folio/service/holdings/HoldingsServiceImpl.java
- src/main/java/org/folio/service/holdings/exception/ProcessInProgressException.java
- src/main/java/org/folio/spring/config/ApplicationConfig.java
- src/main/resources/application.properties
- src/main/resources/templates/db_scripts/create-holdings-status-table.sql
- src/test/java/org/folio/rest/impl/LoadHoldingsImplTest.java
- src/test/java/org/folio/rest/impl/LoadHoldingsStatusImplTest.java
- src/test/java/org/folio/util/HoldingsStatusUtil.java
- src/test/resources/test-application.properties
Add timeout to loading process
Add "updated" attribute to loading status
Add "process_id" column to holdings_status table
process_id contains UUID of current Vert.x instance
Make it so that only process with correct process id can change status
If status was last updated more than 1 hour ago then another process
can safely reset it.
> MODKBEKBJ-324: Add timeout to loading process

- Dockerfile
- descriptors/ModuleDescriptor-template.json
Use new Alpine base docker image with more recent Java 8 (222) with +UseContainerSupport, and JAVA_OPTIONS MaxRAMPercentage to manage container memory.
See notes at [FOLIO-2358](https://issues.folio.org/browse/FOLIO-2358).
Not expecting an actual "review", but this requires an approval so that i can merge and proceed with the remaining steps.
> MODKBEKBJ-338 FOLIO-2358 manage container memory

- ramls/custom-labels.raml
- ramls/examples/customLabels/cl_put_by_id_400_response.json
- ramls/examples/customLabels/cl_put_by_id_422_response.json
- ramls/types/customLabels/customLabelDataAttributes.json
- src/main/java/org/folio/rest/converter/labels/CustomLabelPutRequestConverter.java
- src/main/java/org/folio/rest/converter/labels/CustomLabelPutRequestToRmApiConverter.java
- src/main/java/org/folio/rest/converter/labels/CustomLabelsItemConverter.java
- src/main/java/org/folio/rest/impl/EholdingsCustomLabelsImpl.java
- src/main/java/org/folio/rest/validator/CustomLabelsPutBodyValidator.java
- src/main/java/org/folio/rest/validator/ValidatorUtil.java
- src/test/java/org/folio/rest/converter/labels/CustomLabelPutRequestConverterTest.java
- src/test/java/org/folio/rest/converter/labels/CustomLabelPutRequestToRmApiConverterTest.java
- src/test/java/org/folio/rest/impl/EholdingsCustomLabelsImplTest.java
- src/test/java/org/folio/rest/validator/CustomLabelsPutBodyValidatorTest.java
- src/test/resources/requests/kb-ebsco/custom-labels/put-custom-label-id-five.json
- src/test/resources/requests/kb-ebsco/custom-labels/put-custom-label-invalid-id.json
- src/test/resources/requests/kb-ebsco/custom-labels/put-custom-label-invalid-name.json
- src/test/resources/requests/rmapi/custom-labels/put-custom-labels-two-elements.json
- src/test/resources/responses/kb-ebsco/custom-labels/get-custom-label-single-element-id-five.json
- src/test/resources/responses/kb-ebsco/custom-labels/get-custom-labels-list-updated.json
- src/test/resources/responses/rmapi/custom-labels/get-custom-labels-two-elements.json
Due to https://issues.folio.org/browse/MODKBEKBJ-341 we want to add the ability to update custom labels by id
* updated raml and json example files
* added implementation for PUT /custom-labels/{id}
* added validator for put custom field body
* added converters
* added/updated tests
The returned value of PUT /custom-labels{id} is converted put body with updated values. It was done because of the known but not resolved issue https://corptools.ebsco-gss.net/serviceissues/?si=491744 from RM API side.
> MODKBEKBJ-341 - Custom labels: update custom labels list

- src/main/java/org/folio/repository/holdings/ReportStatus.java
- src/main/java/org/folio/rest/impl/EholdingsResourcesImpl.java
- src/main/java/org/folio/rest/validator/ResourcePutBodyValidator.java
- src/test/java/org/folio/rest/impl/integrationsuite/EholdingsResourcesImplTest.java
- src/test/resources/requests/kb-ebsco/resource/put-managed-resource-is-not-selected.json
- src/test/resources/requests/rmapi/resources/put-managed-resource-is-not-selected.json
- src/test/resources/responses/rmapi/resources/get-managed-resource-updated-response-is-selected-false.json
Make is possible to de-select resource if PUT /resources/{id} request contains userDefinedFields
Allow empty userDefinedFields for PUT /resources/{id} requests where
isSelected=false.
Remove case in which PUT request is not sent to RM API if request is
invalid. This case was used to update tags when isSelected=false, but
now tags are updated in a separate endpoint.
> MODKBEKBJ-346: Fix bug where resource is not removed if request has userDefinedFields

- pom.xml
- src/main/java/org/folio/repository/DbUtil.java
- src/main/java/org/folio/repository/accesstypes/AccessTypeMappingsRepository.java
- src/main/java/org/folio/repository/accesstypes/AccessTypeMappingsRepositoryImpl.java
- src/main/java/org/folio/repository/accesstypes/AccessTypeMappingsTableConstants.java
- src/main/java/org/folio/repository/accesstypes/AccessTypesRepositoryImpl.java
- src/main/java/org/folio/rest/impl/EholdingsPackagesImpl.java
- src/main/java/org/folio/service/accesstypes/AccessTypeMappingsService.java
- src/main/java/org/folio/service/accesstypes/AccessTypeMappingsServiceImpl.java
- src/main/java/org/folio/service/accesstypes/AccessTypesService.java
- src/main/java/org/folio/service/accesstypes/AccessTypesServiceImpl.java
- src/test/java/org/folio/rest/impl/integrationsuite/EholdingsAccessTypesImplTest.java
- src/test/java/org/folio/rest/impl/integrationsuite/EholdingsPackagesTest.java
- src/test/java/org/folio/util/AccessTypesTestUtil.java
Implement story [MODKBEKBJ-380](https://issues.folio.org/browse/MODKBEKBJ-380).
Make not allowable to delete access status type when it is assigned to any record.
* Check assignments of access status type and send error if is assigned
* Extract `AccessTypeMappingsService` from `AccessTypesService`
> MODKBEKBJ-380 Fix delete access type implementation

- pom.xml
- src/main/java/org/folio/rest/converter/common/attr/EmbargoPeriodConverter.java
- src/test/java/org/folio/rest/converter/common/attr/EmbargoPeriodConverterTest.java
Fix the issue when embargo time units received from HoldingsIQ are not converted due to character case.
* modify `EmbargoPeriodConverter` so that it ignores character case of embargo period unit
> MODKBEKBJ-426 Embargo time units are not properly converted

- descriptors/ModuleDescriptor-template.json
- ramls/assigned-users.raml
- ramls/examples/assignedUsers/assigned_users_delete_400_response.json
- ramls/examples/assignedUsers/assigned_users_delete_404_response.json
- src/main/java/org/folio/repository/assigneduser/AssignedUserRepository.java
- src/main/java/org/folio/repository/assigneduser/AssignedUserRepositoryImpl.java
- src/main/java/org/folio/repository/assigneduser/AssignedUsersConstants.java
- src/main/java/org/folio/rest/impl/EholdingsAssignedUsersImpl.java
- src/main/java/org/folio/service/assignedusers/AssignedUsersService.java
- src/main/java/org/folio/service/assignedusers/AssignedUsersServiceImpl.java
- src/test/java/org/folio/rest/impl/integrationsuite/EholdingsAssignedUsersImplTest.java
- src/test/java/org/folio/util/AssignedUsersTestUtil.java
implementation story for https://issues.folio.org/browse/MODKBEKBJ-412
* modified ModuleDescriptor file
* modified assigned-users.raml file
* added implementation for DELETE /eholdings/kb-credentials/{credId}/users/{userId}
* added tests
> MODKBEKBJ-412 - Support DELETE /eholdings/kb-credentials/{credId}/users/{userId} to remove association between user and KB

- descriptors/ModuleDescriptor-template.json
- ramls/examples/proxies/root_proxy_by_credentials_id_get_404_response.json
- ramls/proxies.raml
- ramls/types/proxies/rootProxyData.json
- ramls/types/proxies/rootProxyDataAttributes.json
- src/main/java/org/folio/rest/converter/proxy/RootProxyConverter.java
- src/main/java/org/folio/rest/impl/EHoldingsRootProxyImpl.java
- src/main/java/org/folio/service/rootproxies/RootProxyService.java
- src/main/java/org/folio/service/rootproxies/RootProxyServiceImpl.java
- src/test/java/org/folio/rest/impl/ProxiesTestData.java
- src/test/java/org/folio/rest/impl/RmApiConstants.java
- src/test/java/org/folio/rest/impl/integrationsuite/EHoldingsProxyTypesImplTest.java
- src/test/java/org/folio/rest/impl/integrationsuite/EHoldingsRootProxyImplTest.java
- src/test/resources/responses/kb-ebsco/root-proxy/get-root-proxy-response.json
Implementation for https://issues.folio.org/browse/MODKBEKBJ-417
* modified existing rootProxyAttributes.json file to include credentialsId property.
* added implementation for GET /eholdings/kb-credentials/<credentialsId>/root-proxy
* added tests for GET /eholdings/kb-credentials/<credentialsId>/root-proxy
* modified the logic for GET /eholdings/root-proxy
* updated tests for GET /eholdings/root-proxy
> MODKBEKBJ-417 -Update GET /eholdings/root-proxy to support multiple KB credentials

- src/main/java/org/folio/rest/util/template/RMAPITemplate.java
- src/main/java/org/folio/rest/util/template/RMAPITemplateContext.java
- src/main/java/org/folio/rest/util/template/RMAPITemplateContextBuilder.java
- src/main/java/org/folio/rest/util/template/RMAPITemplateFactory.java
Apply new configuration routine to RMAPITemplate, populate context with credential details (credentialsId, credentialsName) so that other services could filter data appropriately. ([MODKBEKBJ-433](https://issues.folio.org/browse/MODKBEKBJ-433))
- add credentialsId, credentialsName to RMAPITemplateContext
- call `UserKbCredentialsService.findByUser()` inside `RMAPITemplate` to get user credentials and populate `Configuration` in `RMAPITemplateContext`
> MODKBEKBJ-433  Update RMAPITemplate to use new configuration routine

- src/main/java/org/folio/rest/impl/EholdingsStatusImpl.java
- src/main/java/org/folio/spring/config/ApplicationConfig.java
- src/test/java/org/folio/rest/impl/integrationsuite/EholdingsStatusTest.java
Return invalid status from `/eholdings/status` endpoint if no configuration (KB credentials) found for the current user.
* map `Not Found` exception to invalid status
> return invalid status if configuration is not found

- src/main/resources/liquibase/tenant/changelog-3.5.2.xml
- src/main/resources/liquibase/tenant/scripts/v3.5.2/enable-delete-cascade-from-kb-credentials.xml
- src/test/java/org/folio/rest/impl/integrationsuite/EholdingsAccessTypesImplTest.java
- src/test/java/org/folio/rest/impl/integrationsuite/EholdingsKbCredentialsImplTest.java
- src/test/java/org/folio/util/TitlesTestUtil.java
Remove referential integrity restrictions to support deleting KB credentials
* recreate foreign key constraints with `ON DELETE CASCADE` option
> MODKBEKBJ-450 Remove restrictions to support deleting KB credentials

- src/main/resources/liquibase/tenant/scripts/v3.5.2/alter-access-type-mapping-table.xml
Address schema migration issue from Fameflower - Goldenrod
* rename PK of `access_types_mappings`
* add `NOT NULL` to `access_types_mappings.record_type`
> MODKBEKBJ-452  Schema migration issue from Fameflower - Goldenrod

- pom.xml
- src/main/java/org/folio/rest/impl/EholdingsStatusImpl.java
- src/test/java/org/folio/rest/impl/integrationsuite/EholdingsKbCredentialsImplTest.java
- src/test/java/org/folio/rest/impl/integrationsuite/EholdingsStatusTest.java
Change status endpoint behavior to send `isConfigurationValid = false` only when the configuration is really invalid
* change `holdingsiq-client` version to `1.9.1-SNAPSHOT`
* add error mapping
* add tests
> MODKBEKBJ-463 Change status endpoint behavior

- src/main/java/org/folio/rest/impl/EholdingsPackagesImpl.java
- src/main/java/org/folio/rest/util/IdParser.java
- src/main/java/org/folio/rmapi/ResourcesServiceImpl.java
- src/main/java/org/folio/service/holdings/HoldingsService.java
- src/main/java/org/folio/service/holdings/HoldingsServiceImpl.java
- src/main/java/org/folio/service/loader/FilteredEntitiesLoader.java
- src/main/java/org/folio/service/loader/FilteredEntitiesLoaderImpl.java
- src/test/java/org/folio/rest/impl/integrationsuite/EholdingsPackagesTest.java
Fix filtering resources in packages by access types
* Update FilteredEntitiesLoader to load resources instead of titles
> MODKBEKBJ-532 Fix filtering resources in package by access types

- ramls/types/uc/uCSettingsDataAttributes.json
- ramls/uc.raml
- src/main/java/org/folio/client/uc/UCApigeeEbscoClient.java
- src/main/java/org/folio/client/uc/UCApigeeEbscoClientImpl.java
- src/main/java/org/folio/client/uc/model/UCMetricType.java
- src/main/java/org/folio/rest/converter/uc/UCSettingsConverter.java
- src/main/java/org/folio/rest/impl/EholdingsUsageConsolidationImpl.java
- src/main/java/org/folio/rmapi/result/UCSettingsResult.java
- src/main/java/org/folio/service/uc/UCCostPerUseServiceImpl.java
- src/main/java/org/folio/service/uc/UCSettingsService.java
- src/main/java/org/folio/service/uc/UCSettingsServiceImpl.java
- src/main/java/org/folio/spring/config/ApplicationConfig.java
- src/main/java/org/folio/spring/config/UCConfig.java
- src/test/java/org/folio/rest/impl/integrationsuite/EholdingsUsageConsolidationImplTest.java
- src/test/java/org/folio/util/UCSettingsTestUtil.java
Add usage metric type to UC settings response
Add new query parameter `metrictype` to `/uc` and `/<credentialsId>/uc` endpoints. It indicates that metric type should be included or not. It is needed to have the ability to control calling Ebsco endpoint only when usage metric type is needed to UI.
> MODKBEKBJ-538 Add usage metric type to UC settings response

- src/main/java/org/folio/spring/config/UCConfig.java
Fix for https://issues.folio.org/browse/MODKBEKBJ-557
There are two converters that are used inside the mod-kb-ebsco-java module to convert usage consolidation settings -  secured and non-secured. It was a tiny typo in their names, which leads to their misuse.
* fixed usage of converter used for calling APIGEE service
> MODKBEKBJ-557 - CostPerUse API - APIGEE returns error "Unresolved variable : customerownerid"

- src/main/java/org/folio/service/kbcredentials/UserKbCredentialsServiceImpl.java
- src/test/java/org/folio/rest/impl/integrationsuite/EHoldingsProxyTypesImplTest.java
- src/test/java/org/folio/rest/impl/integrationsuite/EHoldingsRootProxyImplTest.java
- src/test/java/org/folio/rest/impl/integrationsuite/EholdingsKbCredentialsImplTest.java
- src/test/java/org/folio/rest/impl/integrationsuite/LoadHoldingsStatusImplTest.java
The message "User credentials not found: userId = <id>"should be changed to provide more information about the reason for the error occurred. There are two situations that can happen to see this error:
* no KB Credentials at all for the system
* there are several KB Credentials created in the system and the user, who is trying to perform a load of holdings is not assigned any credentials.
For more information see a corresponding story - https://issues.folio.org/browse/MODKBEKBJ-536
* changed message to be more informative - "KB Credentials do not exist or user with userId = %s  is not assigned to any available knowledgebase."
> MODKBEKBJ-536 - Load holdings by id doesn't load when there are more than one credentials	

- src/main/java/org/folio/rest/impl/EholdingsTitlesImpl.java
- src/test/java/org/folio/rest/impl/integrationsuite/EholdingsTitlesTest.java
Add ability to include resources in response while search titles by access types
* Return `TitleCollectionResult` when search by access types that has `includeResources` parameter which is processing by `TitleCollectionResultConverter`
> MODKBEKBJ-566 Fix processing include parameter while search titles by access types

- pom.xml
A machine-in-the-middle attack can change the download
to contain malware. Using https will prevent this.
Details: https://issues.folio.org/browse/FOLIO-3044
> FOLIO-3045: Replace http by https in http://maven.indexdata.com/

- src/main/java/org/folio/service/users/UsersLookUpService.java
Fix bug when access status type failed to save
Added accept json header to `UserLookupService` that is required in mod-users GET /user/<id> endpoint
> MODKBEKBJ-586 Add accept json header

- NEWS.md
- src/main/java/org/folio/rest/validator/ProviderTagsPutBodyValidator.java
We should deny updating tags with empty name like "  "
Set isNotBlank instead isNotEmpty
[MODKBEKBJ-600](https://issues.folio.org/browse/MODKBEKBJ-600)
[Differences between blank end empty](https://stackoverflow.com/questions/23419087/stringutils-isblank-vs-string-isempty)
> MODKBEKBJ-600: Providers, deny updating tags with empty name

- NEWS.md
- src/main/java/org/folio/rest/impl/EholdingsPackagesImpl.java
- src/test/java/org/folio/rest/impl/integrationsuite/EholdingsPackagesTest.java
- src/test/resources/requests/kb-ebsco/package/put-package-not-selected-non-empty-fields.json
When isCustom and isSelected are false, we need to met this five conditions:
```
allowKbToAddTitles should be false,
visibilityData.isHidden should be false,
customCoverage should be empty,
packageToken.value should be null.
```
And when one of this conditions not met, server respond with message like: "Package's 'isCustom' and 'isSelected' are 'false'".
the error message is very strict, we need to remove it and display the parameter that prevents the update
Remove pointless message and display real condition that fall
[MODKBEKBJ-598](https://issues.folio.org/browse/MODKBEKBJ-598)
> MODKBEKBJ-598: Packages, clarify error message when unselect non-custom package

- src/main/java/org/folio/rest/validator/AccessTypesBodyValidator.java
- src/main/java/org/folio/rest/validator/CustomPackagePutBodyValidator.java
- src/main/java/org/folio/rest/validator/PackageTagsPutBodyValidator.java
- src/main/java/org/folio/rest/validator/ResourcePostValidator.java
- src/main/java/org/folio/rest/validator/ResourceTagsPutBodyValidator.java
- src/main/java/org/folio/rest/validator/TitleCommonRequestAttributesValidator.java
We can create/update items (packages/resources/tags) with blank name like this " "
But it is forbidden to create empty names like this ""
My suggestion for validation is to use "isBlank()" instead "isEmpty()'
Set isNotBlank instead isNotEmpty
[MODKBEKBJ-602](https://issues.folio.org/browse/MODKBEKBJ-602)
[Differences between blank end empty](https://stackoverflow.com/questions/23419087/stringutils-isblank-vs-string-isempty)
> MODKBEKBJ-602 Validators: Use isBlank instead isEmpty

- src/main/java/org/folio/rest/converter/costperuse/TitleCostPerUseConverter.java
- src/test/java/org/folio/rest/impl/integrationsuite/EholdingsCostperuseImplTest.java
- src/test/resources/responses/rmapi/titles/get-custom-title-with-managed-embargo.json
/costperuse endpoint returns holdingsSгmmary object which doesn't include managed embargo when a resource has it
embargoPeriod object should contain one of:
managed embargo if it exists and custom embargo doesn't exist
custom embargo if it exists
embargoPeriod object should have embargoUnit and embargoValue properties
Task - https://issues.folio.org/browse/MODKBEKBJ-604
Use for verification - https://bugfest-kiwi.folio.ebsco.com/eholdings/resources/19-166-60764
> MODKBEKBJ-604 Return managed embargo in /costperuse endpoint

- src/main/java/org/folio/rest/impl/EholdingsResourcesImpl.java
- src/main/java/org/folio/rmapi/TitlesServiceImpl.java
- src/main/resources/application.properties
- src/test/java/org/folio/rmapi/TitleServiceImplTest.java
Despite the fact that EBSCO HoldingsIQ returns resources with customEmbargoPeriod, kb-ebsco returns null for the same resource
kb-ebsco use cache for fetch TitleSelectedResources.
And cache lives 24 hours, so we get resources with updated customEmbargo after 24 hours
Cache title before user request costperuse
Cut time cache in half
Update cache after resource update
[MODKBEKBJ-618](https://issues.folio.org/browse/MODKBEKBJ-618)
> MODKBEKBJ-618 Null "Custom embargo period"

- Jenkinsfile
- README.md
- ramls/types/uc/costperuse/analysisCostAttributes.json
- ramls/types/uc/costperuse/platformUsage.json
- ramls/types/uc/costperuse/resourceAnalysisCost.json
The doApiLint facility replaces runLintRamlCop
https://dev.folio.org/guides/api-lint/
The doApiDoc facility replaces publishAPI
https://dev.folio.org/guides/api-doc/
The https://dev.folio.org/reference/api/#mod-kb-ebsco-java section of API documentation will be automatically reconfigured:
https://dev.folio.org/reference/api/#explain-gather-config
> MODKBEKBJ-632 FOLIO-3231 Use new api-lint and api-doc CI facilities

- descriptors/ModuleDescriptor-template.json
Fix assigning users to KB credentials error.
- Add "users.item.get" permission to POST "/eholdings/kb-credentials/<credentialsId>/users" endpoint modulePermissions
- Add "users.collection.get" and "usergroups.collection.get" permissions to GET "/eholdings/kb-credentials/<credentialsId>/users" endpoint modulePermissions
- Remove PUT "/eholdings/kb-credentials/<credentialsId>/users/<userId>" enpoint from module description
[MODKBEKBJ-673](https://issues.folio.org/browse/MODKBEKBJ-673)
> MODKBEKBJ-673 User with permission "Settings (eHoldings): Can assign/unassign a user from a KB" can't assign users to KB credentials

- src/main/java/org/folio/service/holdings/AbstractLoadServiceFacade.java
- src/main/java/org/folio/service/holdings/DefaultLoadServiceFacade.java
- src/test/java/org/folio/service/holdings/AbstractLoadServiceFacadeTest.java
- src/test/java/org/folio/service/holdings/DefaultLoadServiceFacadeTest.java
Avoid saving 'Error' status for load holdings job in case holdingsIQ doesn't return status.
- Add 'null' holdingsIQ response handling
- Add retries for querying 'lastHoldingsStatus' for 'null' response
[MODKBEKBJ-668](https://issues.folio.org/browse/MODKBEKBJ-668)
I was unable to reproduce the issue so supposingly holdingsIQ returns 2xx status with empty body in some cases at the start of loading holdings job.
> MODKBEKBJ-668 Loading holdings failed with NullPointer

- docker/.env
- docker/docker-compose.yml
- src/main/resources/liquibase/tenant/scripts/v3.6.6/populate-holdings-and-retry-status.xml
- src/main/resources/templates/db_scripts/create-holdings-status-table.sql
Fix holdings_status migration
* Insert default values into holdings_status and retry_status tables for each kb_credentials
* Update constraints for holdings_status and retry_status tables
* Add docker-compose for testing purposes
> MODKBEKBJ-680 Fix holdings_status migration

- src/main/java/org/folio/rest/converter/costperuse/CostPerUseConverterUtils.java
- src/test/java/org/folio/rest/impl/integrationsuite/EholdingsCostperuseImplTest.java
- src/test/resources/responses/kb-ebsco/costperuse/resources/expected-resource-cost-per-use-with-empty-non-publisher.json
- src/test/resources/responses/uc/titles/get-title-cost-per-use-response-with-empty-non-publisher.json
Fix an error of full text requests by platform usage not displaying when selecting an option, that retrieves empty usage data. The cause of the error was null publisher value which led to NullPointerException.
[MODKBEKBJ-681](https://issues.folio.org/browse/MODKBEKBJ-681)
- null checks when setting usage and cost per use values added
- Test to reflect corresponding changes added
> MODKBEKBJ-681 Full text requests by platform usage display error

- src/main/resources/liquibase/tenant/changelog-3.12.0.xml
- src/main/resources/liquibase/tenant/changelog.xml
- src/main/resources/liquibase/tenant/scripts/v3.12.0/increase-holdings-publication-title-size.xml
- src/main/resources/liquibase/tenant/scripts/v3.12.0/increase-holdings-title-size.xml
While downloading loaded holdings some of holdings have a large publication_title value. (less then 400 characters).
- increase size of publication_title field to 400 characters (was 300)
https://issues.folio.org/browse/MODKBEKBJ-697
> MODKBEKBJ-697 Load Holdings: increase size of publication_title field

- src/main/java/org/folio/repository/holdings/status/HoldingsLoadingStatusFactory.java
- src/main/java/org/folio/rest/util/DateTimeUtil.java
- src/main/java/org/folio/service/holdings/HoldingsServiceImpl.java
- src/test/java/org/folio/rest/impl/TransactionLoadHoldingsImplTest.java
- src/test/java/org/folio/rest/impl/integrationsuite/DefaultLoadHoldingsImplTest.java
- src/test/java/org/folio/rest/impl/integrationsuite/DefaultLoadServiceFacadeTest.java
- src/test/java/org/folio/rest/impl/integrationsuite/EholdingsProxyTypesImplTest.java
- src/test/java/org/folio/rest/impl/integrationsuite/EholdingsRootProxyImplTest.java
- src/test/java/org/folio/rest/impl/integrationsuite/LoadHoldingsStatusImplTest.java
- src/test/java/org/folio/rest/impl/integrationsuite/TransactionLoadServiceFacadeTest.java
- src/test/java/org/folio/util/KbCredentialsTestUtil.java
The POSTGRES_TIMESTAMP_FORMATTER was updated in this PR: [MODKBEKBJ-440](https://github.com/folio-org/mod-kb-ebsco-java/pull/279/files#diff-051a7849d7c856add5af3e74e03a2f09949f32dc49c55c6cd83e6cf187fbc4b8R77).
But some of the clients still have saved old date format in their data bases. So we should support this old format
- Add utility class to works with DateTime
- Trying to parse date by old format if there is parse exception  
https://issues.folio.org/browse/MODKBEKBJ-695
> MODKBEKBJ-695 Load Holdings: Add support for old statuses date format

- descriptors/ModuleDescriptor-template.json
_Missing permission to see and use "Access status type" feature in "eHoldings" app._
_Add "modulePermissions": ["users.item.get"] to handler GET /eholdings/access-types_
https://issues.folio.org/browse/MODKBEKBJ-708
> MODKBEKBJ-708 - Missing permission to see and use "Access status type" feature in "eHoldings" app.

- descriptors/ModuleDescriptor-template.json
_Missing permission to see and use "Access status type" feature in "eHoldings" app._
_Add "modulePermissions": ["users.collection.get"] to handler GET /eholdings/access-types_
https://issues.folio.org/browse/MODKBEKBJ-708
> MODKBEKBJ-708 - Missing permission to see and use "Access status type" feature in "eHoldings" app

- pom.xml
Upgrade netty from 4.1.82.Final to 4.1.86.Final fixing HTTP Response Splitting:
https://nvd.nist.gov/vuln/detail/CVE-2022-41915
Upgrade opencsv from 5.7.0 to 5.7.1.
The opencsv upgrade indirectly upgrades commons-text from 1.9 to 1.10.0. The opencsv dependencies is moved before the commons-configuration2 dependency that would otherwise enforce commons-text 1.9.
The commons-text upgrade fixes Arbitrary Code Execution:
https://nvd.nist.gov/vuln/detail/CVE-2022-42889
Upgrading postgresql from 42.5.0 to 42.5.1 fixes Information Exposure:
https://nvd.nist.gov/vuln/detail/CVE-2022-41946 
> MODKBEKBJ-711: Upgrade netty, postgresql, opencsv fixing vulns

- src/main/java/org/folio/service/holdings/AbstractLoadServiceFacade.java
- src/main/java/org/folio/service/holdings/DefaultLoadServiceFacade.java
- src/test/java/org/folio/rest/impl/integrationsuite/DefaultLoadHoldingsImplTest.java
- src/test/java/org/folio/service/holdings/AbstractLoadServiceFacadeTest.java
- src/test/java/org/folio/service/holdings/DefaultLoadServiceFacadeTest.java
If job was not started, HoldingsIQ will response with empty status body
Return NONE status if status is null. So the job can be started
https://issues.folio.org/browse/MODKBEKBJ-713
> MODKBEKBJ-713 Load holdings: process failing after exceeding status request retries

- .rancher-pipeline.yml
- Dockerfile
- Jenkinsfile
- NEWS.md
- pom.xml
- src/main/java/org/folio/rest/converter/costperuse/export/PackageTitleCostPerUseConverter.java
_Preparing module for next version of java 17 and updating dependecies._
_Updated java to 17_
_Updated folio-di-support version to 2.0.0-SNAPSHOT_
_Updated folio-holdingsiq-client version to 3.0.0-SNAPSHOT_
_Updated spring framework version to 6.0.6_
_Updated log4j version to 2.20.0_
_Updated jetbrains-annotations version to 24.0.1_
_Removed aspectj-maven-plugin groupId com.nickwongdev & v1.12.6_
_Added aspectj-maven-plugin groupId dev.aspectj & v1.13.1_
> MODKBEKBJ-732: Update the module for Java 17 & the latest dependencies

- ramls/types/proxy.json
- src/test/java/org/folio/rest/impl/integrationsuite/EholdingsResourcesImplTest.java
- src/test/resources/requests/kb-ebsco/resource/put-custom-resource-with-proxied-url.json
Avoid an error message when trying to add a title in a package to holdings
Ignore unknown fields in proxy part of the request
[MODKBEKBJ-744](https://issues.folio.org/browse/MODKBEKBJ-744)
> MODKBEKBJ-744: Ignored additional fields in proxy and added related test

- pom.xml
- src/main/java/org/folio/repository/holdings/status/HoldingsLoadingStatusFactory.java
- src/main/java/org/folio/service/holdings/AbstractLoadServiceFacade.java
- src/main/java/org/folio/service/holdings/DefaultLoadServiceFacade.java
- src/main/java/org/folio/service/holdings/HoldingsServiceImpl.java
- src/main/java/org/folio/service/holdings/TransactionLoadServiceFacade.java
- src/main/resources/application.properties
- src/main/resources/templates/db_scripts/update_started_date_before_insertion.sql
- src/test/java/org/folio/service/holdings/AbstractLoadServiceFacadeTest.java
- src/test/java/org/folio/service/holdings/DefaultLoadServiceFacadeTest.java
- src/test/resources/test-application.properties
- Fix trigger before updating holdings_status
- Reduce the size of the page by half after failed retry
- Use the parameter "forse=true" for creating a snapshot.  [FHIQC-33](https://github.com/folio-org/folio-holdingsiq-client/pull/79)
Closes: MODKBEKBJ-747
> fix(load-holdings) Reduce the size of the page by half after failed retry
