.editorconfig
CONTRIBUTING.md
descriptors/DeploymentDescriptor-template.json
src/main/resources/log4j.properties

Add miscellaneous files to project
Use mod-rmb-template to generate files

Add files that were generated by mod-rmb-template

---

Dockerfile
Jenkinsfile

MODKBEKBJ-15 Create dockerfile

---

.gitignore
.gitmodules
NEWS.md
README.md

MODKBEKBJ-16 Add boilterplate files to repo

---

NEWS.md
ramls/eholdings.raml
ramls/packages.raml
ramls/providers.raml
ramls/resources.raml
ramls/titles.raml

* MODKBEKBJ-17 Generate RAML for Providers endpoint
* MODKBEKBJ-22 Generate RAML for Packages endpoint
* MODKBEKBJ-34 Generate RAML for Titles endpoint
* MODKBEKBJ-29 Generate RAML for Resources endpoint
* Generate RAML for root-proxy, configuration, status

MODKBEKBJ-17 MODKBEKBJ-22 MODKBEKBJ-34 MODKBEKBJ-29 Generate raml files

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/rest/converter/RMAPIConfigurationConverter.java
src/main/java/org/folio/rest/impl/EholdingsConfigurationImpl.java

Update code to match schema changes and fix permission typo
Use new model classes

Updates for eholdings configuration

---

descriptors/ModuleDescriptor-template.json
pom.xml
ramls/eholdings.raml
ramls/types/status/status.json
ramls/types/status/statusAttributes.json
ramls/types/status/statusData.json
src/main/java/org/folio/config/RMAPIConfiguration.java
src/main/java/org/folio/config/RMAPIConfigurationServiceCache.java
src/main/java/org/folio/config/RMAPIConfigurationServiceImpl.java
src/main/java/org/folio/config/api/RMAPIConfigurationService.java
src/main/java/org/folio/config/cache/RMAPIConfigurationCache.java
src/main/java/org/folio/config/exception/RMAPIConfigurationInvalidException.java
src/main/java/org/folio/properties/PropertyConfiguration.java
src/main/java/org/folio/rest/converter/RMAPIConfigurationConverter.java
src/main/java/org/folio/rest/converter/StatusConverter.java
src/main/java/org/folio/rest/impl/EholdingsConfigurationImpl.java
src/main/java/org/folio/rest/impl/EholdingsStatusImpl.java
src/main/java/org/folio/rest/impl/InitAPIImpl.java
src/main/java/org/folio/rmapi/RMAPIService.java
src/main/resources/application.properties
src/test/java/org/folio/rest/impl/EholdingsConfigurationTest.java
src/test/java/org/folio/rest/impl/EholdingsStatusTest.java
src/test/java/org/folio/rmapi/config/RMAPIConfigurationServiceTest.java
src/test/java/org/folio/util/TestUtil.java
src/test/resources/responses/rmapi/get-vendors-response.json

Implement GET status endpoint
Implemented caching of current configuration and its status.
Reused method method from "PUT configuration" to validate configuration.

MODKBEKBJ-39: GET /eholdings/status endpoint

---

src/main/java/org/folio/rest/impl/EholdingsPackagesImpl.java

Per https://issues.folio.org/browse/MODKBEKBJ-65 we want to have API tests for POST /eholdings/packages endpoint and for api tests we need to swap error messages for title and details
- swapped error.title with error.details messages

MODKBEKBJ-71 - API Tests DELETE /eholdings/packages/{packageId} endpoint

---

src/main/java/org/folio/config/RMAPIConfigurationServiceCache.java
src/main/java/org/folio/config/RMAPIConfigurationServiceImpl.java
src/main/java/org/folio/config/api/RMAPIConfigurationService.java
src/main/java/org/folio/config/exception/RMAPIConfigurationInvalidException.java
src/main/java/org/folio/config/model/ConfigurationError.java
src/main/java/org/folio/rest/impl/EholdingsConfigurationImpl.java
src/main/java/org/folio/rest/impl/EholdingsStatusImpl.java
src/main/java/org/folio/rest/validator/ValidatorUtil.java

Jira: UIEH-575
Fix issues with error messages in PUT Configuration endpoint.
Change error messages for put eholdings/configuration request to
return list of errors with reasons why configuration is invalid

UIEH-575: Change configuration verification

---

src/main/java/org/folio/rest/impl/EholdingsTitlesImpl.java

Make POST Title to return 404 code if provider or package is not found
Changed exception handling to pass error code from RM API,
so that if provider or package is not found then 404 error will be returned

MODKBEKBJ-84 Adjust error response for title tests

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/rest/impl/EholdingsResourcesImpl.java
src/main/java/org/folio/rest/validator/ResourcePostValidator.java
src/main/java/org/folio/rmapi/RMAPIService.java
src/main/java/org/folio/rmapi/model/ResourceSelectedPayload.java
src/main/java/org/folio/rmapi/result/ObjectsForPostResourceResult.java
src/test/java/org/folio/rest/impl/EholdingsResourcesImplTest.java
src/test/java/org/folio/rest/validator/ResourcePostValidatorTest.java
src/test/resources/requests/kb-ebsco/resource/post-resources-request.json
src/test/resources/requests/rmapi/resources/select-resource-request.json

Implement POST resources endpoint
Send PUT request to RM API with isSelected attribute set to true.
Implement validation to check that package is custom, url is valid and
that title is not already added to package.
Search titles in package by title name to check that title is not added.
When I was investigating Ruby module, I found that validation that checks if title is already added to package doesn't work. Ruby module uses line "package.resources.map(&:titleId).include?(@titleId)", it seems that it always results in false because one parameter is string and another is int.
In java I implemented that check by searching for title name in package with page size 100.

MODKBEKBJ-30: Implement POST /eholdings/resources endpoint

---

src/main/java/org/folio/rest/validator/CustomPackagePutBodyValidator.java
src/main/java/org/folio/rest/validator/PackagesPostBodyValidator.java
src/main/java/org/folio/rest/validator/ResourcePutBodyValidator.java
src/main/java/org/folio/rest/validator/TitlesPostBodyValidator.java

Change attribute length  constraints to correspond to RM API constraints
Change max length constraint for title description to 400,
Change max length of package name to 200

MODKBEKBJ-117: Change max length constraints

---

ramls/types/configuration/configurationAttributes.json
src/main/java/org/folio/rest/impl/EholdingsConfigurationImpl.java
src/main/java/org/folio/rest/validator/ConfigurationPutBodyValidator.java
src/test/java/org/folio/rest/validator/ConfigurationPutBodyValidatorTest.java

Change schema so that schema validation passes.
Configuration doesn't always have all attributes present, if attribute is
not set, then it is not returned in response

MODKBEKBJ-128: Make configuration attributes to be not required

---

src/main/java/org/folio/rest/validator/ValidatorUtil.java

Per https://issues.folio.org/browse/MODKBEKBJ-81 we want to have API Tests for PUT /eholdings/resources/{resourceId} endpoint, in order to improve some tests we need to add validation for identifier id to get response with 422 code instead of 500
- added validation for identifier's "id" property
before validation:
after validation:

MODKBEKBJ-81 - API Tests PUT /eholdings/resources/{resourceId} endpoint

---

NEWS.md
pom.xml

Create release which includes changes for refactor of Postman API tests https://issues.folio.org/browse/MODKBEKBJ-155. Since API Tests (which are run as part of CI/CD pipeline have been updated and require this change) - we want to make sure the releases module includes the necessary dependent change. Additionally,  make release prior to changes to support a persistent layer for tags.
- Follow documented release procedure for mvn module

FOLIO-1753 - Release 2.0.2

---

descriptors/ModuleDescriptor-template.json
pom.xml
ramls/types/providers/providerDataAttributes.json
src/main/java/org/folio/rest/converter/providers/ProviderConverter.java
src/main/java/org/folio/rest/impl/EholdingsProvidersImpl.java
src/main/java/org/folio/rmapi/result/VendorResult.java
src/main/java/org/folio/spring/config/ApplicationConfig.java
src/main/java/org/folio/tag/RecordType.java
src/main/java/org/folio/tag/repository/TagRepository.java
src/main/java/org/folio/tag/repository/TagTableConstants.java
src/main/resources/templates/db_scripts/create-table.sql
src/main/resources/templates/db_scripts/schema.json
src/test/java/org/folio/rest/impl/EholdingsProvidersImplTest.java
src/test/java/org/folio/rest/impl/IntegrationTests.java
src/test/java/org/folio/rest/impl/WireMockTestBase.java

Implement retrieval of tags for provider by provider id.
Used PostgresClient to execute SELECT query and parsed response.

MODKBEKBJ-166 retrieve tags for provider

---

pom.xml
ramls/types/titles/titleData.json
src/main/java/org/folio/rest/converter/titles/TitleConverter.java
src/main/java/org/folio/rest/impl/EholdingsTitlesImpl.java
src/main/java/org/folio/rmapi/result/TitleResult.java
src/test/java/org/folio/rest/impl/EholdingsProvidersImplTest.java
src/test/java/org/folio/rest/impl/EholdingsTitlesTest.java
src/test/java/org/folio/rest/impl/IntegrationTestSuite.java
src/test/java/org/folio/rest/impl/TagsTestUtil.java
src/test/java/org/folio/rest/impl/TestSetUpHelper.java
src/test/java/org/folio/rest/impl/WireMockTestBase.java

Load tags when getting title by id
Loaded tags for title similarly to loading tags for provider
Changed tests to initialize embedded database based on whether or not
test is run inside of test suite or individually. If test class is run
individually (e.g. from IDE) then WireMockTestBase will set up and tear down database.
If test class is run inside of IntegrationTests test suite then IntegrationTests
will be responsible for set up.

MODKBEKBJ-160 Retrieve  tags for title

---

ramls/types/resources/resourceDataAttributes.json
src/main/java/org/folio/rest/converter/resources/ResourceConverter.java
src/main/java/org/folio/rest/impl/EholdingsResourcesImpl.java
src/main/java/org/folio/rmapi/result/ResourceResult.java
src/main/resources/templates/db_scripts/test-data.sql
src/test/java/org/folio/rest/impl/EholdingsResourcesImplTest.java

Return corresponding list of tags when retrieving resource by id
Loaded tags for resource similarly to loading tags for provider

MODKBEKBJ-164 Retrieve tags for resource

---

ramls/types/packages/packageDataAttributes.json
src/main/java/org/folio/rest/converter/packages/PackageConverter.java
src/main/java/org/folio/rest/impl/EholdingsPackagesImpl.java
src/main/java/org/folio/rest/impl/EholdingsResourcesImpl.java
src/main/java/org/folio/rmapi/result/PackageResult.java
src/test/java/org/folio/rest/impl/EholdingsPackagesTest.java

Return corresponding list of tags when retrieving package by id
Loaded tags for package similarly to loading tags for provider

MODKBEKBJ-164 Retrieve tags for package

---

src/main/java/org/folio/rest/converter/providers/ProviderPutRequestConverter.java
src/main/java/org/folio/rest/converter/resources/ResourceRequestConverter.java
src/main/java/org/folio/rest/impl/EholdingsResourcesImpl.java
src/main/java/org/folio/rest/validator/ResourcePutBodyValidator.java
src/main/java/org/folio/rmapi/model/EmbargoPeriod.java
src/test/java/org/folio/rest/converter/ResourceRequestConverterTest.java
src/test/resources/requests/rmapi/resources/put-custom-resource-is-selected-multiple-attributes.json
src/test/resources/requests/rmapi/resources/put-managed-resource-is-selected-multiple-attributes.json
src/test/resources/responses/rmapi/resources/get-custom-resource-updated-response.json

Jira: MODKBEKBJ-168
Fix bug with PUT request for resource
Merged existing resource attributes with attributes in PUT request.
If PUT request doesn't have an attribute then request to RM API will
be populated with old value for this attribute, so that the value will
not be changed

MODKBEKBJ-168: Fix bug where missing attributes caused error on PUT

---

src/main/java/org/folio/rest/impl/EholdingsProvidersImpl.java
src/main/java/org/folio/tag/repository/TagRepository.java
src/main/java/org/folio/tag/repository/TagTableConstants.java
src/main/resources/templates/db_scripts/schema.json
src/main/resources/templates/db_scripts/test-data.sql
src/test/java/org/folio/rest/impl/EholdingsProvidersImplTest.java
src/test/java/org/folio/rest/impl/TagsTestUtil.java
src/test/java/org/folio/rest/impl/WireMockTestBase.java
src/test/resources/requests/rmapi/vendors/put-vendor-token-proxy-with-tags.json

Per https://issues.folio.org/browse/MODKBEKBJ-161 we want to have a functionality to assign and unassign tags for Provider entity
added assign/unassign functionality for Provider by PostgresClient

MODKBEKBJ-161 - Tags: assign/unassign tags to Provider record

---

NEWS.md
pom.xml

Create release which includes fixes related to integration of mod-kb-ebsco-java and ui-eholdings. https://issues.folio.org/browse/MODKBEKBJ-168. 
Additional changes include preliminary updates for tags
- Follow documented release procedure for mvn module

Release 2.0.3

---

src/main/java/org/folio/rest/impl/EholdingsResourcesImpl.java
src/test/java/org/folio/rest/impl/EholdingsResourcesImplTest.java

Modify resource tags on PUT and DELETE requests
Added calls to TagsRepository on corresponding requests

MODKBEKBJ-165 assing/unassign resource tags

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/rest/converter/titles/TitlePutRequestConverter.java
src/main/java/org/folio/rest/impl/EholdingsTitlesImpl.java
src/test/java/org/folio/rest/impl/EholdingsTitlesTest.java

Allow assigning/unassigning tags to title with PUT titles/{id} endpoint
Inserted tags into database after successful update of title on put.
Added small fixes to PUT titles/{id} endpoint

MODKBEKBJ-163 assign tags to title

---

src/main/resources/templates/db_scripts/create-table.sql

Per https://issues.folio.org/browse/MODKBEKBJ-198, tenant init fails due to our existing schema. Fix the schema so that tenant init can be done repeatedly without failure.
- Add/Drop columns and indexes only after checking for their existence.
https://github.com/folio-org/raml-module-builder - specifically postgressql integration

Update create table schema

---

pom.xml

In preparation for upcoming release update snapshot version from 2.0.4 to 2.1.0 so that 2.1.0 can be used as the Q1 release version.
Once updated -- will follow standard release steps
https://dev.folio.org/guidelines/release-procedures/

Update version from 2.0.4-SNAPSHOT to 2.1.0-SNAPSHOT in prep for upcoming release

---

src/main/java/org/folio/rest/converter/resources/ResourceRequestConverter.java
src/test/java/org/folio/rest/converter/resources/ResourceRequestConverterTest.java

Fix switching to managed coverage dates.
https://issues.folio.org/browse/MODKBEKBJ-205
Fixing check  on empty list for coverage data list.
Refactoring tests

MODKBEKBJ-205 Switching to managed coverage dates does not work

---

src/main/java/org/folio/rest/converter/common/attr/ContributorsConverterPair.java
src/test/java/org/folio/rest/impl/EholdingsTitlesTest.java
src/test/resources/requests/kb-ebsco/title/put-title.json
src/test/resources/requests/rmapi/resources/put-custom-resource-is-selected-multiple-attributes.json
src/test/resources/responses/kb-ebsco/resources/expected-custom-resource.json
src/test/resources/responses/kb-ebsco/resources/expected-managed-resource.json
src/test/resources/responses/kb-ebsco/resources/expected-resource-by-id.json
src/test/resources/responses/kb-ebsco/titles/expected-title-by-id-for-resource.json
src/test/resources/responses/kb-ebsco/titles/expected-title-by-id.json
src/test/resources/responses/kb-ebsco/titles/expected-updated-title.json
src/test/resources/responses/kb-ebsco/titles/get-created-title-response.json
src/test/resources/responses/kb-ebsco/titles/get-title-by-id-include-resources-response.json
src/test/resources/responses/kb-ebsco/titles/get-title-by-id-invalid-include-response.json
src/test/resources/responses/rmapi/resources/get-custom-resource-updated-response.json

Updates for https://issues.folio.org/browse/MODKBEKBJ-209
* updated ContributorsConverterPair to use a lowercase method
* updated tests

MODKBEKBJ-209 - Do not capitalize contributor type

---

src/main/java/org/folio/rest/util/template/RMAPITemplate.java
src/main/java/org/folio/rest/util/template/RMAPITemplateFactory.java
src/main/java/org/folio/rmapi/PackageServiceImpl.java
src/main/java/org/folio/rmapi/cache/PackageCacheKey.java
src/main/java/org/folio/spring/config/ApplicationConfig.java
src/main/resources/application.properties
src/test/java/org/folio/rest/impl/WireMockTestBase.java
src/test/java/org/folio/rmapi/PackageServiceImplTest.java

MODKBEKBJ-211
Add option to cache packages to PackageServiceImpl
Add caching for packages
Add option to cache packages to PackageServiceImpl
Use VertxCache class to implement caching

MODKBEKBJ-211 Add package cache

---

src/main/java/org/folio/rmapi/PackageServiceImpl.java
src/test/java/org/folio/rest/impl/EholdingsPackagesTest.java
src/test/java/org/folio/rmapi/PackageServiceImplTest.java

There is an issue with processing packages that are retrieved with an error

MODKBEKBJ-188 Fix error handling when getting packages by tags

---

src/main/java/org/folio/rest/util/template/RMAPITemplateContextBuilder.java
src/main/java/org/folio/rmapi/ResourcesServiceImpl.java
src/main/java/org/folio/rmapi/cache/ResourceCacheKey.java
src/main/java/org/folio/spring/config/ApplicationConfig.java
src/main/resources/application.properties
src/test/java/org/folio/rest/impl/WireMockTestBase.java
src/test/java/org/folio/rmapi/ResourceServiceImplTest.java

MODKBEKBJ-222 Add cache for resources

---

NEWS.md
pom.xml

Create Q2.1 release which includes the following changes since Q1
* https://issues.folio.org/browse/MODKBEKBJ-186  	- Tags: add endpoint to return all tags assigned to records of particular type(s)
* https://issues.folio.org/browse/MODKBEKBJ-188 - Tags: search packages by tag filter only
* https://issues.folio.org/browse/MODKBEKBJ-201 - Spike: Define technical approach for using RM API to filter results by tags
* https://issues.folio.org/browse/MODKBEKBJ-205 - Switching to managed coverage dates does not work
* https://issues.folio.org/browse/MODKBEKBJ-208 - Contributor Type: Filter out any contributor type that is not Author, Editor,Illustrator
* https://issues.folio.org/browse/MODKBEKBJ-209 - Do not capitalize contributor type
* https://issues.folio.org/browse/MODKBEKBJ-210 - Tags: add …

Release 2.3.0 (Q2.1)

---

pom.xml

fix for https://issues.folio.org/browse/MODKBEKBJ-250

MODKBEKBJ-250 - Fix security vulnerabilities reported in jackson-databind >= 2.0.0, < 2.9.9

---

src/main/java/org/folio/repository/tag/TagRepository.java
src/main/java/org/folio/repository/tag/TagRepositoryImpl.java
src/main/java/org/folio/repository/tag/TagTableConstants.java
src/main/java/org/folio/rest/converter/resources/CommonResourceConverter.java
src/main/java/org/folio/rest/converter/titles/TitleConverter.java
src/main/java/org/folio/rest/impl/EholdingsTitlesImpl.java
src/main/java/org/folio/rmapi/result/TitleResult.java
src/test/java/org/folio/rest/impl/EholdingsTitlesTest.java
src/test/java/org/folio/rest/impl/ResourcesTestData.java
src/test/java/org/folio/rest/impl/TitlesTestData.java
src/test/resources/responses/kb-ebsco/titles/get-title-by-id-include-resources-with-tags-response.json

Displaying included into title resources with tags.
https://issues.folio.org/browse/MODKBEKBJ-242
Adding new request to DB. Attaching tags from DB to included into title resource.
Adding and adjusting tests.

MODKBEKBJ-242 Title | List of Packages | Display assigned resource tags

---

descriptors/ModuleDescriptor-template.json
ramls/examples/tags/unique_tags_get_200_response.json
ramls/examples/tags/unique_tags_get_400_response.json
ramls/tags.raml
ramls/types/tags/tagUniqueCollection.json
ramls/types/tags/tagUniqueCollectionItem.json
src/main/java/org/folio/repository/tag/TagRepository.java
src/main/java/org/folio/repository/tag/TagRepositoryImpl.java
src/main/java/org/folio/repository/tag/TagTableConstants.java
src/main/java/org/folio/rest/converter/tags/TagsConverters.java
src/main/java/org/folio/rest/impl/EholdingsTagsImpl.java
src/test/java/org/folio/rest/impl/EholdingsTagsImplTest.java

Providing new endpoint for list of unique tags.
GET /eholdings/tags/summary
Adding new tags response schemes.
Providing functionality of returning unique tags from database.

MODKBEKBJ-263 Add method to return list of Tags available for an entity type

---

pom.xml

Upgrading jackson lib to version 2.9.9.2

MODKBEKBJ-296 Upgrade jackson lib to version 2.9.9.2

---

descriptors/ModuleDescriptor-template.json

Change frequency of loading to 5 days
Modify _timer interface in ModuleDescriptor-template.json

MODKBEKBJ-309: Change frequency of loading to 5 days

---

pom.xml
src/main/resources/templates/db_scripts/drop_set_id_in_jsonb.sql
src/main/resources/templates/db_scripts/schema.json
src/main/resources/templates/db_scripts/update_started_date_before_insertion.sql

Due to https://issues.folio.org/browse/MODKBEKBJ-312 we want to be able to use new capabilities of the RMB module.
* updated RMB to 27.0.0

MODKBEKBJ-312 - Update RMB to version 27.0.0

---

pom.xml
ramls/types/packages/packagePutDataAttributes.json
src/main/java/org/folio/rest/converter/packages/PackageRequestConverter.java
src/test/java/org/folio/rest/impl/EholdingsPackagesTest.java
src/test/resources/requests/kb-ebsco/package/put-package-selected.json
src/test/resources/requests/rmapi/packages/put-package-is-selected.json

Support "isFullPackage" attribute
Add isFullPackage to schema for PUT /packages/{id} endpoint,
Pass isFullPackage to RM API

MODKBEKBJ-311: Support "isFullPackage" attribute

---

pom.xml

fix for https://issues.folio.org/browse/MODKBEKBJ-315
* fixed jackson-databind version

MODKBEKBJ-315 - Fix Security Vulnerability

---

pom.xml
src/test/java/org/folio/rest/impl/LoadHoldingsImplTest.java
src/test/java/org/folio/rest/impl/LoadHoldingsStatusImplTest.java
src/test/java/org/folio/rest/impl/LoadServiceFacadeImplTest.java
src/test/java/org/folio/util/KBTestUtil.java

fix for  https://issues.folio.org/browse/MODKBEKBJ-316
* upgrade rmb to 27.1.1
- vert.x changes due to [SendContext](https://github.com/vert-x3/wiki/wiki/3.6.0-Deprecations-and-breaking-changes)

MODKBEKBJ-316 - Upgrade RMB to 27.1.1

---

pom.xml

Fix for https://issues.folio.org/browse/MODKBEKBJ-329
* updated jackson-databind version

MODKBEKBJ-329 - Fix Security Vulnerability

---

ramls/types/resources/resourceDataAttributes.json
src/main/java/org/folio/rest/converter/resources/CommonResourceConverter.java
src/test/resources/responses/kb-ebsco/titles/get-title-by-id-include-resources-response.json
src/test/resources/responses/rmapi/titles/get-title-by-id-response.json

Make custom label available in /titles/{id}?include=resources
Transfer userDefinedField attributes to response

MODKBEKBJ-336: Add custom labels to GET /titles/{id}?include=resources

---

src/test/resources/responses/kb-ebsco/resources/expected-custom-resource.json
src/test/resources/responses/kb-ebsco/resources/expected-managed-resource.json
src/test/resources/responses/kb-ebsco/resources/expected-resource-by-id.json
src/test/resources/responses/kb-ebsco/resources/expected-resources-by-package-id.json
src/test/resources/responses/rmapi/resources/get-custom-resource-updated-response.json
src/test/resources/responses/rmapi/resources/get-managed-resource-updated-response.json
src/test/resources/responses/rmapi/resources/get-resource-by-id-success-response.json
src/test/resources/responses/rmapi/resources/get-resources-by-package-id-response.json
src/test/resources/responses/rmapi/titles/get-title-by-id-for-post-request.json

Update unit tests for custom labels in 
/resources/{id}, 
/packages/{id}/resources 
/packages/{id}?include=resources

MODKBEKBJ-337: Update unit tests for custom labels in /resources/{id}, /packages/{id}/resources and /packages/{id}?include=resources

---

descriptors/ModuleDescriptor-template.json
ramls/custom-labels.raml
ramls/examples/customLabels/cl_collection_get_200_response.json
ramls/examples/customLabels/cl_get_by_id_400_response.json
ramls/examples/customLabels/cl_get_put_delete_by_id_404_response.json
ramls/examples/customLabels/cl_item_get_200_response.json
ramls/examples/customLabels/cl_put_by_id_200_response.json
ramls/examples/customLabels/cl_put_by_id_400_response.json
ramls/examples/customLabels/cl_put_request.json
ramls/providers.raml
ramls/types/customLabels/customLabel.json
ramls/types/customLabels/customLabelCollectionItem.json
ramls/types/customLabels/customLabelDataAttributes.json
ramls/types/customLabels/customLabelPutRequest.json
ramls/types/customLabels/customLabelsCollection.json
ramls/types/resources/resourceDataAttributes.json
ramls/types/resources/resourcePutDataAttributes.json
src/main/java/org/folio/rest/converter/labels/CustomLabelsCollectionConverter.java
src/main/java/org/folio/rest/converter/labels/CustomLabelsItemConverter.java
src/main/java/org/folio/rest/impl/EholdingsCustomLabelsImpl.java
src/test/java/org/folio/rest/converter/labels/CustomLabelsCollectionConverterTest.java
src/test/java/org/folio/rest/converter/labels/CustomLabelsItemCollectionTest.java
src/test/java/org/folio/rest/impl/EholdingsCustomLabelsImplTest.java
src/test/java/org/folio/rest/impl/IntegrationTestSuite.java
src/test/resources/requests/kb-ebsco/custom-labels/put-custom-label.json
src/test/resources/responses/kb-ebsco/custom-labels/get-custom-labels-list.json
src/test/resources/responses/rmapi/custom-labels/get-custom-labels.json

Implementation for https://issues.folio.org/browse/MODKBEKBJ-340 for addition of custom labels functionality defined https://docs.google.com/presentation/d/1WYCM9D7MzD32nNzoJ1kXfVDSTRJHaTxW5nVKoAtAiIs/edit#slide=id.p
* updated ModuleDescriptor with additional endpoints for custom labels
* created custom-labels raml file to define endpoints
* implemented GET /custom-labels collection
* added tests
* Ruby implementation - https://github.com/folio-org/mod-kb-ebsco/pull/86
* RM API - https://developer.ebsco.com/interactive/holdingsiq#/

MODKBEKBJ-340 - Custom labels: retrieve custom labels list

---

pom.xml
ramls/types/resources/resourcePutDataAttributes.json
src/main/java/org/folio/rest/converter/resources/ResourceRequestConverter.java
src/main/java/org/folio/rest/converter/titles/TitlePutRequestConverter.java
src/main/java/org/folio/rest/validator/ResourcePutBodyValidator.java
src/test/java/org/folio/rest/converter/resources/ResourceRequestConverterTest.java
src/test/java/org/folio/rest/impl/EholdingsResourcesImplTest.java
src/test/java/org/folio/rest/impl/ResourcesTestData.java
src/test/java/org/folio/rest/validator/ResourcePutBodyValidatorTest.java
src/test/resources/requests/kb-ebsco/resource/put-managed-resource.json
src/test/resources/requests/rmapi/resources/put-custom-resource-is-selected-multiple-attributes.json
src/test/resources/requests/rmapi/resources/put-managed-resource-is-selected-multiple-attributes.json

Update userDefinedFields on PUT /resources/{id}
Pass userDefinedFields to RM API
Validate userDefinedFields
Add unit tests

MODKBEKBJ-335: Update userDefinedFields on PUT /resources/{id}

---

ramls/custom-labels.raml
src/main/java/org/folio/rest/converter/labels/CustomLabelConverter.java
src/main/java/org/folio/rest/impl/EholdingsCustomLabelsImpl.java
src/test/java/org/folio/rest/converter/labels/CustomLabelsItemCollectionTest.java
src/test/java/org/folio/rest/impl/EholdingsCustomLabelsImplTest.java
src/test/resources/responses/kb-ebsco/custom-labels/get-custom-label-single-element.json
src/test/resources/responses/rmapi/custom-labels/get-custom-labels-with-single-element.json

implementation for https://issues.folio.org/browse/MODKBEKBJ-342
* added implementation for GET /custom-labels/{id}
* added converter for single item
* added tests

MODKBEKBJ-342 - Custom labels: retrieve custom label by id

---

ramls/types/titles/titlePutData.json
ramls/types/titles/titlePutDataAttributes.json
src/main/java/org/folio/rest/converter/resources/CommonResourceConverter.java
src/main/java/org/folio/rest/converter/resources/ResourceRequestConverter.java
src/main/java/org/folio/rest/converter/titles/TitlePostRequestConverter.java
src/main/java/org/folio/rest/converter/titles/TitlePutRequestConverter.java
src/main/java/org/folio/rest/impl/EholdingsTitlesImpl.java
src/main/java/org/folio/rest/model/TitleCommonRequestAttributes.java
src/main/java/org/folio/rest/validator/ResourcePutBodyValidator.java
src/main/java/org/folio/rest/validator/TitleCommonRequestAttributesValidator.java
src/main/java/org/folio/rest/validator/TitlesPostBodyValidator.java
src/main/java/org/folio/rest/validator/ValidationConstants.java
src/test/java/org/folio/rest/converter/holdings/HoldingsCollectionItemConverterTest.java
src/test/java/org/folio/rest/converter/resources/ResourceRequestConverterTest.java
src/test/java/org/folio/rest/converter/titles/TitlePutRequestConverterTest.java
src/test/java/org/folio/rest/impl/EholdingsTitlesTest.java
src/test/java/org/folio/rest/impl/ResourcesTestData.java
src/test/java/org/folio/rest/validator/TitlePostBodyValidatorTest.java
src/test/resources/requests/kb-ebsco/title/post-title-request.json
src/test/resources/responses/rmapi/titles/get-title-by-id-for-post-request.json

Add custom labels to POST /titles endpoint
Create separate schema for PUT and POST /titles requests,
Add TitleCommonRequestAttributes interface for common attributes
Adjust unit tests

MODKBEKBJ-334: Add userDefinedFields to POST /titles

---

ramls/custom-labels.raml
ramls/examples/customLabels/cl_delete_by_id_400_response.json
src/main/java/org/folio/rest/impl/EholdingsCustomLabelsImpl.java
src/test/java/org/folio/rest/impl/EholdingsCustomLabelsImplTest.java
src/test/resources/requests/rmapi/custom-labels/put-custom-label-one-element.json

Implementation for https://issues.folio.org/browse/MODKBEKBJ-343
* added implementation for DELETE /custom-labels{id}
* added tests

MODKBEKBJ-343 - Custom labels: delete custom label

---

NEWS.md
pom.xml
src/main/resources/application.properties

Create mod-kb-ebsco-java release according to issue [MODKBEKBJ-361](https://issues.folio.org/browse/MODKBEKBJ-361)

Release 3.2.0

---

src/main/java/org/folio/rest/impl/EholdingsPackagesImpl.java
src/test/java/org/folio/rest/impl/integrationsuite/EholdingsPackagesTest.java
src/test/resources/requests/kb-ebsco/package/put-package-selected-with-access-type.json
src/test/resources/requests/kb-ebsco/package/put-package-selected.json
src/test/resources/requests/rmapi/packages/put-package-is-selected.json

[JIRA MODKBEKBJ-353](https://issues.folio.org/browse/MODKBEKBJ-353)
Update access type mapping on the edit managed selected package. 
* Update PUT package request.
* Add tests.

MODKBEKBJ-353 Set access type on update not custom package

---

ramls/types/resources/resourcePutDataAttributes.json
ramls/types/resources/resourceRelationships.json
src/main/java/org/folio/rest/converter/resources/ResourceResultConverter.java
src/main/java/org/folio/rest/impl/EholdingsPackagesImpl.java
src/main/java/org/folio/rest/impl/EholdingsProvidersImpl.java
src/main/java/org/folio/rest/impl/EholdingsResourcesImpl.java
src/main/java/org/folio/rest/impl/EholdingsTitlesImpl.java
src/main/java/org/folio/rest/util/ExceptionMappers.java
src/main/java/org/folio/rest/validator/ResourcePutBodyValidator.java
src/main/java/org/folio/rmapi/result/Accessible.java
src/main/java/org/folio/rmapi/result/PackageResult.java
src/main/java/org/folio/rmapi/result/ResourceResult.java
src/main/java/org/folio/rmapi/result/Tagable.java
src/main/java/org/folio/rmapi/result/TitleResult.java
src/main/java/org/folio/rmapi/result/VendorResult.java
src/main/java/org/folio/service/loader/RelatedEntitiesLoader.java
src/main/java/org/folio/service/loader/RelatedEntitiesLoaderImpl.java
src/test/java/org/folio/rest/impl/integrationsuite/EholdingsResourcesImplTest.java
src/test/java/org/folio/rest/validator/ResourcePutBodyValidatorTest.java
src/test/resources/requests/kb-ebsco/resource/put-managed-resource-with-invalid-access-type.json
src/test/resources/requests/kb-ebsco/resource/put-managed-resource-with-missing-access-type.json
src/test/resources/requests/kb-ebsco/resource/put-resource-with-access-type.json
src/test/resources/responses/kb-ebsco/resources/expected-managed-resource-with-access-type.json

Implement story [MODKBEKBJ-354](https://issues.folio.org/browse/MODKBEKBJ-354).
Implement the possibility to set access status type when update resource.
* Update ramls for resource
* Update `GET, PUT, DELETE` requests in `EholdingsResourcesImpl`
* Update `ResourceResultConverter` converter
* Make refactoring of `ResourcePutBodyValidator`
* Add new tests

MODKBEKBJ-354 Set access type on update resource

---

ramls/types/accessTypes/accessTypeCollectionItem.json
src/main/java/org/folio/repository/accesstypes/AccessTypeMappingsRepository.java
src/main/java/org/folio/repository/accesstypes/AccessTypeMappingsRepositoryImpl.java
src/main/java/org/folio/repository/accesstypes/AccessTypeMappingsTableConstants.java
src/main/java/org/folio/service/accesstypes/AccessTypeMappingsService.java
src/main/java/org/folio/service/accesstypes/AccessTypeMappingsServiceImpl.java
src/main/java/org/folio/service/accesstypes/AccessTypesServiceImpl.java
src/test/java/org/folio/rest/impl/integrationsuite/EholdingsAccessTypesImplTest.java

Return number of records used by each Access Type ([JIRA](https://issues.folio.org/browse/MODKBEKBJ-378))
* Update raml
* Update GET endpoints to return number of records used by each Access Type
* Update tests

MODKBEKBJ-378 add number of records to GET endpoints

---

ramls/packages.raml
src/main/java/org/folio/rest/impl/EholdingsPackagesImpl.java
src/test/java/org/folio/rest/impl/integrationsuite/EholdingsPackagesTest.java
src/test/java/org/folio/rest/impl/integrationsuite/EholdingsTitlesTest.java
src/test/java/org/folio/util/ResourcesTestUtil.java

Implement the ability to find all titles based on an assigned access status type(s) in package.
* Update `packages.raml`
* Update `EholdingsPackagesImpl` to support the feature
* Add tests

MODKBEKBJ-376 Filter titles by access type into package

---

pom.xml
src/main/java/org/folio/rest/converter/titles/TitleConverter.java
src/test/java/org/folio/rest/impl/integrationsuite/EholdingsTitlesTest.java
src/test/resources/responses/kb-ebsco/titles/get-title-by-id-include-resources-response.json
src/test/resources/responses/rmapi/titles/get-title-by-id-response-with-resources.json

Apply sorting to the list of packages in title record in this order
1. Packages Starting with Special Chars (Etc #,&,(….)
2. Packages Starting with Numbers
3. Packages Starting with English names (Sorted by A-Z)
4. Packages Starting with Foreign Characters.
5. Packages without Package Names
* update `TitleConverter` with sorting by package name
* update unit tests (`pom.xml` was changed to have ability testing not-Latin test data)

MODKBEKBJ-384 Apply sort to packages

---

src/main/resources/templates/db_scripts/schema.json

Fix migrating from v3.2.0 to v3.3.1

MODKBEKBJ-392 Fix migrating from v3.2.0 to v3.3.1

---

descriptors/ModuleDescriptor-template.json
ramls/assigned-users.raml
ramls/examples/assignedUsers/assigned_users_post_201_response.json
ramls/examples/assignedUsers/assigned_users_post_400_response.json
ramls/examples/assignedUsers/assigned_users_post_404_response.json
ramls/examples/assignedUsers/assigned_users_post_422_response.json
ramls/examples/assignedUsers/assigned_users_post_request.json
ramls/types/assignedUsers/assignedUser.json
ramls/types/assignedUsers/assignedUserPostRequest.json
src/main/java/org/folio/repository/assigneduser/AssignedUserRepository.java
src/main/java/org/folio/repository/assigneduser/AssignedUserRepositoryImpl.java
src/main/java/org/folio/repository/assigneduser/AssignedUsersConstants.java
src/main/java/org/folio/rest/converter/assignedusers/AssignedUserCollectionItemConverter.java
src/main/java/org/folio/rest/impl/EholdingsAssignedUsersImpl.java
src/main/java/org/folio/service/assignedusers/AssignedUsersService.java
src/main/java/org/folio/service/assignedusers/AssignedUsersServiceImpl.java
src/test/java/org/folio/rest/impl/WireMockTestBase.java
src/test/java/org/folio/rest/impl/integrationsuite/EholdingsAssignedUsersImplTest.java
src/test/java/org/folio/rest/impl/integrationsuite/EholdingsKbCredentialsImplTest.java
src/test/java/org/folio/util/AssignedUsersTestUtil.java

Support POST /eholdings/kb-credentials/{credId}/users to associate user with KB
* Add ramls definitions
* Implement endpoint
* Add tests

MODKBEKBJ-410 Implement new endpoint to save assigned user.

---

ramls/assigned-users.raml
ramls/examples/assignedUsers/assigned_users_put_400_response.json
ramls/examples/assignedUsers/assigned_users_put_404_response.json
ramls/examples/assignedUsers/assigned_users_put_422_response.json
ramls/examples/assignedUsers/assigned_users_put_request.json
ramls/types/assignedUsers/assignedUserPutRequest.json
src/main/java/org/folio/repository/SqlQueryHelper.java
src/main/java/org/folio/repository/assigneduser/AssignedUserRepository.java
src/main/java/org/folio/repository/assigneduser/AssignedUserRepositoryImpl.java
src/main/java/org/folio/repository/assigneduser/AssignedUsersConstants.java
src/main/java/org/folio/rest/impl/EholdingsAssignedUsersImpl.java
src/main/java/org/folio/service/assignedusers/AssignedUsersService.java
src/main/java/org/folio/service/assignedusers/AssignedUsersServiceImpl.java
src/test/java/org/folio/rest/impl/integrationsuite/EholdingsAssignedUsersImplTest.java
src/test/java/org/folio/rest/impl/integrationsuite/EholdingsKbCredentialsImplTest.java
src/test/java/org/folio/util/AssignedUsersTestUtil.java
src/test/java/org/folio/util/KbCredentialsTestUtil.java

Support PUT /eholdings/kb-credentials/{credId}/users/{userId} to update details of user associated with KB
* add raml definitions
* implement endpoint
* add tests

MODKBEKBJ-411 Implement endpoint to update assigned user

---

descriptors/ModuleDescriptor-template.json

MODKBEKBJ-415 Update module descriptor

---

descriptors/ModuleDescriptor-template.json
ramls/access-types.raml
src/main/java/org/folio/repository/accesstypes/AccessTypesRepository.java
src/main/java/org/folio/repository/accesstypes/AccessTypesRepositoryImpl.java
src/main/java/org/folio/repository/accesstypes/AccessTypesTableConstants.java
src/main/java/org/folio/rest/impl/EholdingsAccessTypesImpl.java
src/main/java/org/folio/rest/impl/EholdingsPackagesImpl.java
src/main/java/org/folio/rest/impl/EholdingsResourcesImpl.java
src/main/java/org/folio/service/accesstypes/AccessTypesService.java
src/main/java/org/folio/service/accesstypes/AccessTypesServiceImpl.java
src/main/java/org/folio/service/accesstypes/AccessTypesServiceOldImpl.java
src/test/java/org/folio/rest/impl/integrationsuite/EholdingsAccessTypesImplTest.java
src/test/java/org/folio/util/AccessTypesTestUtil.java

Update `GET /eholdings/access-types/{id}` to support multiple KB credentials
* update ramls and module descriptor
* update `GET /eholdings/access-types/{id}` endpoint
* create new `GET /eholdings/kb-credentials/{id}/access-types/{id}` endpoint

MODKBEKBJ-404 Implement new endpoint to get access type by id

---

src/test/java/org/folio/rest/impl/integrationsuite/EholdingsKbCredentialsImplTest.java
src/test/java/org/folio/util/HoldingsRetryStatusTestUtil.java
src/test/java/org/folio/util/HoldingsStatusUtil.java

Implementation story for https://issues.folio.org/browse/MODKBEKBJ-428. The main part was added along with #267 and this pull request ads test(s).
* added tests

MODKBEKBJ-428 - Set loading status "Not Started" on KB Credentials creation

---

src/main/java/org/folio/repository/DbUtil.java
src/main/java/org/folio/repository/accesstypes/AccessTypesRepositoryImpl.java
src/main/java/org/folio/repository/assigneduser/AssignedUserRepository.java
src/main/java/org/folio/repository/assigneduser/AssignedUserRepositoryImpl.java
src/main/java/org/folio/repository/assigneduser/AssignedUsersConstants.java
src/main/java/org/folio/service/kbcredentials/UserKbCredentialsServiceImpl.java
src/main/java/org/folio/spring/config/ApplicationConfig.java
src/test/java/org/folio/rest/impl/integrationsuite/EholdingsKbCredentialsImplTest.java
src/test/java/org/folio/util/KbCredentialsTestUtil.java

Additional check to make sure a user has no access if there is a single KB credentials defined and the user is not amongst those who is assigned.

MODKBEKBJ-432 Verify single creds with other user

---

src/main/resources/liquibase/tenant/changelog-3.5.0.xml
src/main/resources/liquibase/tenant/scripts/v3.5.0/_clean-up.xml
src/main/resources/liquibase/tenant/scripts/v3.5.0/add-kb-credentials-to-packages.xml
src/main/resources/liquibase/tenant/scripts/v3.5.0/add-kb-credentials-to-providers.xml
src/main/resources/liquibase/tenant/scripts/v3.5.0/add-kb-credentials-to-resources.xml
src/main/resources/liquibase/tenant/scripts/v3.5.0/add-kb-credentials-to-titles.xml
src/main/resources/liquibase/tenant/scripts/v3.5.0/alter-access-type-mapping-table.xml
src/main/resources/liquibase/tenant/scripts/v3.5.0/alter-access-types-table.xml
src/main/resources/liquibase/tenant/scripts/v3.5.0/alter-holdings-status-audit-table.xml
src/main/resources/liquibase/tenant/scripts/v3.5.0/alter-holdings-status-table.xml
src/main/resources/liquibase/tenant/scripts/v3.5.0/alter-holdings-table.xml
src/main/resources/liquibase/tenant/scripts/v3.5.0/alter-retry-status-table.xml
src/main/resources/liquibase/tenant/scripts/v3.5.0/alter-transaction-ids-table.xml
src/main/resources/liquibase/tenant/scripts/v3.5.0/create-assigned-users-table.xml
src/main/resources/liquibase/tenant/scripts/v3.5.0/create-kb-credentials-table.xml
src/test/java/org/folio/rest/impl/WireMockTestBase.java

Data migration scripts added
- Place the necessary data migration statements into Liquibase change logs

MODKBEKBJ-444 Data migration

---

src/main/resources/liquibase/tenant/changelog-3.5.0.xml
src/main/resources/liquibase/tenant/scripts/v3.5.0/_clean-up.xml
src/main/resources/liquibase/tenant/scripts/v3.5.0/_set-up.xml
src/main/resources/liquibase/tenant/scripts/v3.5.0/alter-access-types-table.xml
src/main/resources/liquibase/tenant/scripts/v3.5.0/alter-holdings-status-table.xml
src/main/resources/liquibase/tenant/scripts/v3.5.0/create-holding-status-audit-trigger.xml
src/main/resources/templates/db_scripts/change_function_owner.sql
src/main/resources/templates/db_scripts/schema.json

Resolve any issues found during data migration verification

MODKBEKBJ-444 Update migration scripts

---

src/main/java/org/folio/repository/DbUtil.java
src/main/java/org/folio/repository/accesstypes/AccessTypesRepositoryImpl.java
src/main/java/org/folio/repository/kbcredentials/KbCredentialsRepositoryImpl.java
src/main/resources/liquibase/tenant/changelog-3.5.2.xml
src/main/resources/liquibase/tenant/scripts/v3.5.2/alter-access-type-mapping-table.xml
src/main/resources/liquibase/tenant/scripts/v3.5.2/alter-kb-credentials-table.xml
src/test/java/org/folio/rest/impl/integrationsuite/EHoldingsProxyTypesImplTest.java
src/test/java/org/folio/rest/impl/integrationsuite/EHoldingsRootProxyImplTest.java
src/test/java/org/folio/rest/impl/integrationsuite/EholdingsKbCredentialsImplTest.java
src/test/java/org/folio/util/KbCredentialsTestUtil.java

Do not allow multiples of the same credentials to be saved. Validate: CustomerID and URL
* add unique constraint for customerId + URL

MODKBEKBJ-449  Prevent duplicate KB credentials

---

src/main/java/org/folio/service/kbcredentials/KbCredentialsServiceImpl.java

small fixes to save kbCredentials process

small fixes to save kbCredentials process

---

src/main/java/org/folio/rest/impl/EholdingsResourcesImpl.java
src/test/java/org/folio/rest/impl/integrationsuite/EholdingsResourcesImplTest.java

Return a better message when the title is no longer in a package
* Update message
* Update tests

MODKBEKBJ-472 Return a better message for resource 404

---

pom.xml

MODKBEKBJ-467  mod-kb-ebsco-java: Update to RMB v31.x

---

pom.xml
src/main/java/org/folio/rest/impl/LoadHoldingsImpl.java

* add fixes for mod-kb-ebsco-java v3.5.3 to master

Add mod-kb-ebsco-java v3.5.3 to master

---

pom.xml
src/main/java/org/folio/client/uc/UCAuthEbscoClient.java
src/main/java/org/folio/client/uc/UCAuthEbscoClientImpl.java
src/main/java/org/folio/client/uc/UCAuthServiceClient.java
src/main/java/org/folio/client/uc/UCAuthServiceClientImpl.java
src/main/java/org/folio/client/uc/UCAuthToken.java
src/main/java/org/folio/repository/DbUtil.java
src/main/java/org/folio/repository/uc/DbUCCredentials.java
src/main/java/org/folio/repository/uc/UCCredentialsRepository.java
src/main/java/org/folio/repository/uc/UCCredentialsRepositoryImpl.java
src/main/java/org/folio/repository/uc/UCCredentialsTableConstants.java
src/main/java/org/folio/service/uc/UCAuthService.java
src/main/java/org/folio/service/uc/UCAuthServiceImpl.java
src/main/java/org/folio/service/uc/UcAuthenticationException.java
src/main/java/org/folio/spring/config/ApplicationConfig.java
src/main/resources/application.properties
src/main/resources/liquibase/tenant/changelog-3.6.0.xml
src/main/resources/liquibase/tenant/scripts/v3.6.0/create-usage-consolidation-credentials-table.xml
src/test/java/org/folio/rest/impl/WireMockTestBase.java
src/test/java/org/folio/service/uc/UCAuthServiceImplTest.java
src/test/java/org/folio/service/users/UsersLookUpServiceTest.java
src/test/java/org/folio/util/UCCredentialsTestUtil.java
src/test/resources/test-application.properties

Implement Usage Consolidation auth service.
* create new db table to store credentials
* implement repository and auth service
* implement auth service client to request token
* add tests

MODKBEKBJ-496 Implement Usage Consolidation auth service

---

descriptors/ModuleDescriptor-template.json
ramls/examples/uc/uc_settings_patch_404_response.json
ramls/examples/uc/uc_settings_patch_422_response.json
ramls/examples/uc/uc_settings_patch_request.json
ramls/types/uc/month.json
ramls/types/uc/platformType.json
ramls/types/uc/uCSettingsDataAttributes.json
ramls/types/uc/uCSettingsPatchRequest.json
ramls/types/uc/uCSettingsPatchRequestData.json
ramls/types/uc/uCSettingsPatchRequestDataAttributes.json
ramls/uc.raml
src/main/java/org/folio/client/uc/UCApigeeEbscoClient.java
src/main/java/org/folio/client/uc/UCApigeeEbscoClientImpl.java
src/main/java/org/folio/client/uc/UCAuthEbscoClientImpl.java
src/main/java/org/folio/client/uc/UCConfiguration.java
src/main/java/org/folio/repository/uc/DbUCSettings.java
src/main/java/org/folio/repository/uc/UCSettingsRepository.java
src/main/java/org/folio/repository/uc/UCSettingsRepositoryImpl.java
src/main/java/org/folio/repository/uc/UCSettingsTableConstants.java
src/main/java/org/folio/rest/converter/uc/UCSettingsConverter.java
src/main/java/org/folio/rest/impl/EholdingsKbCredentialsUCImpl.java
src/main/java/org/folio/service/uc/UCSettingsService.java
src/main/java/org/folio/service/uc/UCSettingsServiceImpl.java
src/main/java/org/folio/spring/config/ApplicationConfig.java
src/main/resources/application.properties
src/test/java/org/folio/rest/impl/integrationsuite/EholdingsKbCredentialsUCImplTest.java
src/test/java/org/folio/service/uc/UCAuthServiceImplTest.java
src/test/java/org/folio/util/UCSettingsTestUtil.java
src/test/resources/test-application.properties

Implement endpoint PATCH /eholdings/kb-credentials/<id>/uc
* create raml definition
* implement apigee client for verification customer key
* implement endpoint
* create tests

MODKBEKBJ-495 Implement PATCH UC Settings

---

descriptors/ModuleDescriptor-template.json
ramls/costperuse.raml
ramls/examples/costPerUse/package_resources_cost_per_use_200_response.json
ramls/traits/costPerUsePageable.raml
ramls/types/uc/costperuse/resourceAnalysisCost.json
ramls/types/uc/costperuse/resourceCostPerUseCollection.json
ramls/types/uc/costperuse/resourceCostPerUseCollectionItem.json
src/main/java/org/folio/client/uc/UCApigeeEbscoClient.java
src/main/java/org/folio/client/uc/UCApigeeEbscoClientImpl.java
src/main/java/org/folio/client/uc/model/UCTitlePackageId.java
src/main/java/org/folio/rest/converter/costperuse/ResourceCostPerUseCollectionConverter.java
src/main/java/org/folio/rest/impl/EholdingsCostperuseImpl.java
src/main/java/org/folio/rest/util/IdParser.java
src/main/java/org/folio/rmapi/result/ResourceCostPerUseCollectionResult.java
src/main/java/org/folio/service/uc/UCCostPerUseService.java
src/main/java/org/folio/service/uc/UCCostPerUseServiceImpl.java
src/test/java/org/folio/rest/impl/integrationsuite/EholdingsCostperuseImplTest.java
src/test/resources/responses/uc/title-packages/get-multiply-title-packages-cost-per-use-for-package-response.json

Implement package's resources cost-per-use endpoint
* Implement endpoint
* Create tests

MODKBEKBJ-500 Implement package's resources cost-per-use endpoint

---

pom.xml

Update HoldingsIQ client library version to enable response logging

MODKBEKBJ-505 Log responses from HoldingsIQ/MODKBEKBJ

---

src/main/java/org/folio/properties/customlabels/CustomLabelsProperties.java
src/main/java/org/folio/rest/validator/CustomLabelsPutBodyValidator.java
src/main/java/org/folio/spring/config/ApplicationConfig.java
src/main/resources/application.properties
src/test/java/org/folio/rest/validator/CustomLabelsPutBodyValidatorTest.java
src/test/resources/test-application.properties

Change custom labels' max label length to `200`
* Create properties class for all custom labels properties
* Fix custom label validator
* Fix tests

MODKBEKBJ-516 Change custom labels' max label length

---

src/main/java/org/folio/properties/customlabels/CustomLabelsProperties.java
src/main/java/org/folio/rest/validator/ResourcePutBodyValidator.java
src/main/java/org/folio/rest/validator/TitlesPostBodyValidator.java
src/main/java/org/folio/rest/validator/ValidationConstants.java
src/main/java/org/folio/spring/config/ApplicationConfig.java
src/main/resources/application.properties
src/test/java/org/folio/rest/validator/CustomLabelsPutBodyValidatorTest.java
src/test/java/org/folio/rest/validator/ResourcePutBodyValidatorTest.java
src/test/java/org/folio/rest/validator/TitlePostBodyValidatorTest.java
src/test/resources/test-application.properties

Change custom labels' max value length to `500`
* add an appropriate property
* fix tests

MODKBEKBJ-517 Change custom labels' max value length

---

src/main/java/org/folio/properties/customlabels/CustomLabelsProperties.java
src/main/java/org/folio/rest/converter/resources/ResourceCollectionItemConverters.java
src/main/java/org/folio/rest/converter/resources/ResourceConverter.java
src/main/java/org/folio/rest/validator/CustomLabelsPutBodyValidator.java
src/main/java/org/folio/rest/validator/ResourcePutBodyValidator.java
src/main/java/org/folio/rest/validator/TitlesPostBodyValidator.java
src/main/java/org/folio/rest/validator/ValidationConstants.java
src/main/java/org/folio/spring/config/ApplicationConfig.java
src/main/resources/application.properties
src/test/java/org/folio/rest/validator/CustomLabelsPutBodyValidatorTest.java
src/test/java/org/folio/rest/validator/ResourcePutBodyValidatorTest.java
src/test/java/org/folio/rest/validator/TitlePostBodyValidatorTest.java
src/test/resources/test-application.properties

Update custom labels length limits

Custom labels limit update

---

pom.xml
src/test/java/org/folio/rest/impl/integrationsuite/EholdingsPackagesTest.java

fix for https://issues.folio.org/browse/MODKBEKBJ-515
* changed title search type to 'contains'

MODKBEKBJ-515 - GET Titles search | change searchtype from advanced to contains

---

descriptors/ModuleDescriptor-template.json
ramls/uc.raml
src/main/java/org/folio/rest/impl/EholdingsUsageConsolidationImpl.java
src/test/java/org/folio/rest/impl/IntegrationTestSuite.java
src/test/java/org/folio/rest/impl/integrationsuite/EholdingsUsageConsolidationImplTest.java
src/test/java/org/folio/util/UCSettingsTestUtil.java

Implement `/eholdings/uc` endpoint

MODKBEKBJ-523 Implement /eholdings/uc endpoint

---

src/main/java/org/folio/common/ListUtils.java
src/main/java/org/folio/repository/SqlQueryHelper.java
src/main/java/org/folio/repository/holdings/DbHoldingInfo.java
src/main/java/org/folio/repository/holdings/HoldingsRepository.java
src/main/java/org/folio/repository/holdings/HoldingsRepositoryImpl.java
src/main/java/org/folio/repository/holdings/HoldingsTableConstants.java
src/main/java/org/folio/repository/holdings/status/retry/RetryStatusRepositoryImpl.java
src/main/java/org/folio/repository/holdings/status/retry/RetryStatusTableConstants.java
src/main/java/org/folio/repository/titles/TitlesRepositoryImpl.java
src/main/java/org/folio/rest/converter/holdings/HoldingCollectionItemConverter.java
src/main/java/org/folio/rest/converter/resources/ResourceCollectionResultConverter.java
src/main/java/org/folio/rest/util/IdParser.java
src/main/java/org/folio/service/holdings/HoldingsServiceImpl.java
src/main/java/org/folio/service/uc/UCCostPerUseServiceImpl.java
src/main/resources/liquibase/tenant/changelog-3.6.0.xml
src/main/resources/liquibase/tenant/scripts/v3.6.0/alter-holdings-types.xml
src/test/java/org/folio/rest/converter/packages/PackageResponseConverterTest.java
src/test/java/org/folio/rest/impl/integrationsuite/EholdingsCostperuseImplTest.java
src/test/java/org/folio/util/HoldingsTestUtil.java

Improve performance of holdings queries
* change type of package_id, vendor_id, and title_id columns to integer
* update related code
* use prepared queries in HoldingsRepository

MODKBEKBJ-527 Improve performance of holdings queries

---

ramls/types/uc/costperuse/holdingsAnalysisCostAttributes.json
src/main/java/org/folio/rest/converter/costperuse/TitleCostPerUseConverter.java
src/test/resources/responses/kb-ebsco/costperuse/titles/expected-title-cost-per-use.json

Add resourceId to title's cost-per-use response
* update raml definition and converter

MODKBEKBJ-533 Add resourceId to title's cost-per-use response

---

src/main/java/org/folio/repository/packages/PackageRepositoryImpl.java
src/main/java/org/folio/repository/packages/PackageTableConstants.java
src/test/java/org/folio/rest/impl/integrationsuite/EholdingsProvidersImplTest.java

Fix filtering packages by tags
* update select query to aggregate tags in one column

MODKBEKBJ-522 Fix filtering packages by tags

---

src/main/resources/liquibase/tenant/scripts/v3.5.0/_clean-up.xml
src/main/resources/liquibase/tenant/scripts/v3.5.0/_set-up.xml
src/main/resources/liquibase/tenant/scripts/v3.5.0/alter-holdings-status-table.xml

Fix migration scripts
Create a new procedure that checks if a trigger exists for a specific table.

MODKBEKBJ-537 Fix migration scripts

---

src/main/java/org/folio/repository/holdings/status/HoldingsStatusRepositoryImpl.java
src/main/java/org/folio/rest/impl/LoadHoldingsImpl.java
src/main/java/org/folio/rest/util/template/RMAPITemplate.java
src/main/java/org/folio/service/holdings/HoldingsService.java
src/main/java/org/folio/service/holdings/HoldingsServiceImpl.java
src/test/java/org/folio/rest/impl/integrationsuite/DefaultLoadHoldingsImplTest.java
src/test/java/org/folio/util/HoldingsStatusUtil.java

MODKBEKBJ-528 Fix hanged holding loading

---

src/main/java/org/folio/common/LogUtils.java
src/main/java/org/folio/repository/accesstypes/AccessTypeMappingsRepositoryImpl.java
src/main/java/org/folio/repository/accesstypes/AccessTypesRepositoryImpl.java
src/main/java/org/folio/repository/assigneduser/AssignedUserRepositoryImpl.java
src/main/java/org/folio/repository/holdings/HoldingsRepositoryImpl.java
src/main/java/org/folio/repository/holdings/status/HoldingsStatusRepositoryImpl.java
src/main/java/org/folio/repository/holdings/status/audit/HoldingsStatusAuditRepositoryImpl.java
src/main/java/org/folio/repository/holdings/status/retry/RetryStatusRepositoryImpl.java
src/main/java/org/folio/repository/holdings/transaction/TransactionIdRepositoryImpl.java
src/main/java/org/folio/repository/kbcredentials/KbCredentialsRepositoryImpl.java
src/main/java/org/folio/repository/packages/PackageRepositoryImpl.java
src/main/java/org/folio/repository/providers/ProviderRepositoryImpl.java
src/main/java/org/folio/repository/resources/ResourceRepositoryImpl.java
src/main/java/org/folio/repository/tag/TagRepositoryImpl.java
src/main/java/org/folio/repository/titles/TitlesRepositoryImpl.java
src/main/java/org/folio/repository/users/UsersRepositoryImpl.java

Implementation story for - https://issues.folio.org/browse/MODKBEKBJ-549
* changed log level to debug for holdings loading classes.

MODKBEKBJ-549 - Suppress unnecessary logs

---

src/main/java/org/folio/rest/converter/costperuse/TitleCostPerUseConverter.java
src/test/java/org/folio/rest/impl/integrationsuite/EholdingsCostperuseImplTest.java
src/test/resources/responses/kb-ebsco/costperuse/titles/expected-title-cost-per-use-with-no-usage.json
src/test/resources/responses/uc/titles/get-empty-title-cost-per-use-response.json

MODKBEKBJ-559 Fix title cost-per-use NPE

---

src/main/resources/liquibase/tenant/changelog-3.6.6.xml
src/main/resources/liquibase/tenant/changelog.xml
src/main/resources/liquibase/tenant/scripts/v3.6.6/populate-holdings-and-retry-status.xml

Fix holdings loading after dummy credentials update
Update migration scripts to populate holdings status and retry status for dummy credentials

MODKBEKBJ-556 Fix holdings loading after dummy credentials update

---

descriptors/ModuleDescriptor-template.json
ramls/examples/uc/uc_settings_get_200_response.json
ramls/examples/uc/uc_settings_key_get_200_response.json
ramls/types/uc/uCSettingsDataAttributes.json
ramls/types/uc/uCSettingsKey.json
ramls/types/uc/uCSettingsKeyDataAttributes.json
ramls/uc.raml
src/main/java/org/folio/rest/converter/uc/UCSettingsConverter.java
src/main/java/org/folio/rest/impl/EholdingsUsageConsolidationImpl.java
src/main/java/org/folio/service/uc/UCSettingsService.java
src/main/java/org/folio/service/uc/UCSettingsServiceImpl.java
src/main/java/org/folio/spring/config/UCConfig.java
src/test/java/org/folio/rest/impl/integrationsuite/EholdingsUsageConsolidationImplTest.java
src/test/java/org/folio/util/UCSettingsTestUtil.java

Add the ability to see the UC ID  
Create endpoint that returns customer key `/eholdings/kb-credentials/<id>/uc/key`

MODKBEKBJ-560 Create endpoint that returns customer key

---

descriptors/ModuleDescriptor-template.json
ramls/examples/kbCredentials/kb_credentials_get_200_response.json
ramls/examples/kbCredentials/kb_credentials_key_get_200_response.json
ramls/kb-credentials.raml
ramls/types/kbCredentials/kbCredentialsDataAttributes.json
ramls/types/kbCredentials/kbCredentialsKey.json
ramls/types/kbCredentials/kbCredentialsKeyDataAttributes.json
src/main/java/org/folio/rest/converter/kbcredentials/KbCredentialsConverter.java
src/main/java/org/folio/rest/impl/EholdingsKbCredentialsImpl.java
src/main/java/org/folio/service/holdings/HoldingsService.java
src/main/java/org/folio/service/holdings/HoldingsServiceImpl.java
src/main/java/org/folio/service/kbcredentials/KbCredentialsService.java
src/main/java/org/folio/service/kbcredentials/KbCredentialsServiceImpl.java
src/main/java/org/folio/spring/config/ApplicationConfig.java
src/test/java/org/folio/rest/impl/integrationsuite/EholdingsKbCredentialsImplTest.java

Create endpoint that returns decrypted KB key
New endpoint was implemented `/eholdings/kb-credentials/<id>/key`

MODKBEKBJ-561 Create endpoint that return decrypted KB key

---

PERSONAL_DATA_DISCLOSURE.md

Place a copy of the personal data disclosure form at the top level of the module github repository to disclose stored types of personal data
* add PERSONAL_DATA_DISCLOSURE.md file

MODKBEKBJ-563 Add personal data disclosure form

---

src/main/java/org/folio/rest/converter/costperuse/ResourceCostPerUseCollectionConverter.java
src/main/java/org/folio/rmapi/result/ResourceCostPerUseCollectionResult.java
src/main/java/org/folio/service/uc/UCCostPerUseServiceImpl.java
src/test/java/org/folio/rest/impl/integrationsuite/EholdingsCostperuseImplTest.java

Fix bug when in the response of resources' cost-per-use collection doesn't exist the percentage of usage.

MODKBEKBJ-570 Fix percent of usage calculation

---

src/main/java/org/folio/service/loader/FilteredEntitiesLoaderImpl.java
src/test/java/org/folio/rest/impl/integrationsuite/EholdingsTitlesTest.java
src/test/resources/responses/kb-ebsco/titles/expected-tagged-titles-with-resources.json
src/test/resources/responses/kb-ebsco/titles/expected-tagged-titles.json
src/test/resources/responses/rmapi/titles/get-title-by-id-2-response.json

Support filtering of Resources in Titles by Tags or Access Types
Add filtering title's resources in logic of retrieving titles by tags or access types

MODKBEKBJ-570 Filter resources in title

---

src/main/java/org/folio/service/loader/FilteredEntitiesLoaderImpl.java
src/test/java/org/folio/rest/impl/ResourcesTestData.java
src/test/java/org/folio/rest/impl/integrationsuite/EholdingsTitlesTest.java

Fix duplicate titles on GET by tags with included resources

MODKBEKBJ-578 Fix duplicate titles on GET by tags with included resources

---

src/main/java/org/folio/service/holdings/AbstractLoadServiceFacade.java
src/main/java/org/folio/service/holdings/DefaultLoadServiceFacade.java
src/main/resources/application.properties
src/test/resources/responses/rmapi/holdings/status/get-status-completed.json
src/test/resources/test-application.properties

Decrease size of holdings loading pages

MODKBEKBJ-577 Decrease size of holdings loading pages

---

descriptors/ModuleDescriptor-template.json
ramls/examples/uc/uc_credentials_get_200_response.json
ramls/types/uc/uCCredentialsPresence.json
ramls/uc.raml
src/main/java/org/folio/rest/impl/UsageConsolidationCredentialsApi.java
src/main/java/org/folio/service/uc/UCAuthService.java
src/main/java/org/folio/service/uc/UCAuthServiceImpl.java
src/test/java/org/folio/rest/impl/IntegrationTestSuite.java
src/test/java/org/folio/rest/impl/integrationsuite/UsageConsolidationCredentialsApiTest.java
src/test/java/org/folio/util/UCCredentialsTestUtil.java

Implement an endpoint that will indicate that cliend_id and client_secret exist in the system
* create raml definitions
* implement API interface and make changes to AuthService
* add API tests

MODKBEKBJ-576 Implement GET UC credentials endpoint

---

descriptors/ModuleDescriptor-template.json
ramls/examples/uc/uc_credentials_put_422_response.json
ramls/examples/uc/uc_credentials_put_request.json
ramls/types/uc/uCCredentials.json
ramls/uc.raml
src/main/java/org/folio/repository/uc/UCCredentialsRepository.java
src/main/java/org/folio/repository/uc/UCCredentialsRepositoryImpl.java
src/main/java/org/folio/repository/uc/UCCredentialsTableConstants.java
src/main/java/org/folio/rest/impl/UsageConsolidationCredentialsApi.java
src/main/java/org/folio/service/uc/UCAuthService.java
src/main/java/org/folio/service/uc/UCAuthServiceImpl.java
src/test/java/org/folio/rest/impl/integrationsuite/EholdingsUsageConsolidationImplTest.java
src/test/java/org/folio/rest/impl/integrationsuite/UsageConsolidationCredentialsApiTest.java
src/test/java/org/folio/util/UCCredentialsTestUtil.java

Implement an endpoint that will update cliend_id and client_secret in the system
* create raml definitions
* implement API interface and make changes to AuthService
* add API tests

MODKBEKBJ-579 Implement PUT UC credentials endpoint

---

pom.xml
ramls/tags.raml
src/main/java/org/folio/service/users/UsersLookUpService.java
src/test/java/org/folio/rest/impl/integrationsuite/EholdingsAccessTypesImplTest.java
src/test/java/org/folio/service/users/UsersLookUpServiceTest.java

Upgrade to RMB v33
https://issues.folio.org/browse/MODKBEKBJ-581

MODKBEKBJ-581 Upgrade to RMB v33

---

src/main/resources/liquibase/tenant/scripts/v3.5.0/alter-holdings-status-table.xml
src/main/resources/liquibase/tenant/scripts/v3.5.2/alter-access-type-mapping-table.xml

Fix constraint checks in migration scripts
Added schema condition to checks

MODKBEKBJ-584 Fix constraint checks in migration scripts

---

src/main/java/org/folio/rest/converter/resources/ResourceRequestConverter.java
src/test/java/org/folio/rest/impl/integrationsuite/EholdingsResourcesImplTest.java
src/test/resources/requests/rmapi/resources/put-managed-resource-is-selected-multiple-attributes.json

fix for story https://issues.folio.org/browse/MODKBEKBJ-589
* fixed an editing for url for custom title
_Describe the research stage. Add links to blog posts, patterns, libraries or addons used to solve this problem._

MODKBEKBJ-589 - Сannot edit the Custom URL in the package-title record

---

src/main/java/org/folio/rest/converter/resources/ResourceRequestConverter.java
src/test/java/org/folio/rest/converter/resources/ResourceRequestConverterTest.java
src/test/java/org/folio/rest/impl/integrationsuite/EholdingsResourcesImplTest.java
src/test/resources/requests/rmapi/resources/put-managed-resource-is-selected-multiple-attributes.json

fix for https://issues.folio.org/browse/MODKBEKBJ-592
- fixed update of url within managed title in managed package

MODKBEKBJ-592 - Cannot edit a package-title (aka resource) record

---

pom.xml

Log4j vulnerability verification and correction

MODKBEKBJ-605 Log4j vulnerability verification and correction

---

NEWS.md
src/main/java/org/folio/rest/converter/resources/ResourceRequestConverter.java
src/test/java/org/folio/rest/converter/resources/ResourceRequestConverterTest.java

Have an ability to remove custom embargo.
- remove filling custom embargo with old values when no embargo passed
- update tests
[MODKBEKBJ-609](https://issues.folio.org/browse/MODKBEKBJ-609)

MODKBEKBJ-609 Unable to update title-package record when user removes custom embargo

---

pom.xml
src/test/java/org/folio/service/uc/UCAuthServiceImplTest.java

Update to the latest RMB 33.2.* release.
See details: https://github.com/folio-org/raml-module-builder/blob/master/doc/upgrading.md

MODKBEKBJ-614 Upgrade to RAML Module Builder 33.2.4

---

src/main/java/org/folio/repository/holdings/HoldingsRepositoryImpl.java
src/main/java/org/folio/repository/holdings/status/HoldingsStatusRepositoryImpl.java
src/main/java/org/folio/repository/tag/TagRepositoryImpl.java

PostgresClient provides new methods to work with transactions. 
The purpose of this task is to use these methods instead of the deprecated executeInTransaction method.
- Use `PgClient.withTransaction()` instead of `DbUtils.executeInTransaction()`
[MODKBEKBJ-627](https://issues.folio.org/browse/MODKBEKBJ-627)

MODKBEKBJ-627 Replace deprecated executeInTransaction method

---

NEWS.md
ramls/traits/filterable.raml
ramls/types/packages/contentTypeEnum.json
src/main/java/org/folio/rest/converter/common/ConverterConsts.java
src/main/java/org/folio/rest/converter/packages/PackageConverterUtils.java
src/main/java/org/folio/rest/util/RestConstants.java
src/test/java/org/folio/rest/converter/packages/PackageRequestConverterTest.java
src/test/java/org/folio/rest/impl/integrationsuite/EholdingsPackagesTest.java
src/test/java/org/folio/rest/validator/CustomPackagePutBodyValidatorTest.java
src/test/java/org/folio/rest/validator/PackagePostValidatorTest.java
src/test/resources/requests/kb-ebsco/package/post-package-request.json
src/test/resources/requests/kb-ebsco/package/post-package-with-access-type-request.json
src/test/resources/requests/kb-ebsco/package/put-package-custom-multiple-attributes.json
src/test/resources/requests/kb-ebsco/package/put-package-custom-with-access-type.json
src/test/resources/requests/rmapi/packages/post-package.json
src/test/resources/requests/rmapi/packages/put-package-custom.json
src/test/resources/responses/kb-ebsco/resources/expected-resource-by-id-with-all-objects.json
src/test/resources/responses/kb-ebsco/resources/expected-resource-by-id-with-package.json
src/test/resources/responses/rmapi/packages/get-package-by-id-for-resource.json

Add new package content  types
[MODKBEKBJ-624](https://issues.folio.org/browse/MODKBEKBJ-624)

MODKBEKBJ-624 Include additional package content types

---

descriptors/ModuleDescriptor-template.json

Define `kb-ebsco.user-kb-credential.get` permission

MODKBEKBJ-628 Define `kb-ebsco.user-kb-credential.get` permission

---

descriptors/ModuleDescriptor-template.json
ramls/examples/uc/uc_credentials_client_id_get_200_response.json
ramls/types/uc/uCCredentialsClientId.json
ramls/uc.raml
src/main/java/org/folio/rest/impl/UsageConsolidationCredentialsApi.java
src/main/java/org/folio/service/uc/UCAuthService.java
src/main/java/org/folio/service/uc/UCAuthServiceImpl.java
src/test/java/org/folio/rest/impl/integrationsuite/UsageConsolidationCredentialsApiTest.java

Implement GET /eholdings/uc-credentials/clientId to get usage consolidation id in plain text
[MODKBEKBJ-637](https://issues.folio.org/browse/MODKBEKBJ-637)

Modkbekbj-637 Implement GET /eholdings/uc-credentials/clientId endpoint

---

.gitmodules
pom.xml
src/main/java/org/folio/client/uc/UCApigeeEbscoClientImpl.java
src/main/java/org/folio/repository/RecordType.java
src/main/java/org/folio/repository/accesstypes/AccessTypeMappingsTableConstants.java
src/main/java/org/folio/repository/accesstypes/AccessTypesTableConstants.java
src/main/java/org/folio/repository/holdings/LoadStatus.java
src/main/java/org/folio/repository/holdings/ReportStatus.java
src/main/java/org/folio/rest/converter/assignedusers/UserCollectionDataConverter.java
src/main/java/org/folio/rest/impl/LoadHoldingsImpl.java
src/main/java/org/folio/rest/util/ErrorUtil.java
src/main/java/org/folio/rest/util/TenantUtil.java
src/main/java/org/folio/service/accesstypes/AccessTypeMappingsServiceImpl.java
src/main/java/org/folio/service/accesstypes/AccessTypesServiceImpl.java
src/main/java/org/folio/service/assignedusers/AssignedUsersServiceImpl.java
src/main/java/org/folio/service/currencies/CurrenciesServiceImpl.java
src/main/java/org/folio/service/kbcredentials/KbCredentialsServiceImpl.java
src/main/java/org/folio/service/kbcredentials/UserKbCredentialsServiceImpl.java
src/main/java/org/folio/service/locale/LocaleSettingsServiceImpl.java
src/main/java/org/folio/service/uc/UCAuthServiceImpl.java
src/main/java/org/folio/service/uc/UCSettingsServiceImpl.java
src/test/java/org/folio/rest/impl/IntegrationTestSuite.java
src/test/java/org/folio/rest/impl/WireMockTestBase.java
src/test/java/org/folio/rest/impl/integrationsuite/EHoldingsProxyTypesImplTest.java
src/test/java/org/folio/rest/impl/integrationsuite/EHoldingsRootProxyImplTest.java
src/test/java/org/folio/rest/impl/integrationsuite/EholdingsAssignedUsersImplTest.java
src/test/java/org/folio/rest/impl/integrationsuite/EholdingsPackagesTest.java
src/test/java/org/folio/rest/validator/AssignedUsersBodyValidatorTest.java
src/test/java/org/folio/rmapi/TitleServiceImplTest.java
src/test/java/org/folio/service/users/UsersLookUpServiceTest.java

Upgrade RMB and Vert.x version
* Upgrade dependencies
* Create util method for tenant ID fetching from headers (RMB method requires now to have case insensitive map)
* Fix several code smells

MODKBEKBJ-659 Upgrade RMB and Vert.x version

---

pom.xml
src/main/java/org/folio/repository/assigneduser/DbAssignedUser.java
src/main/java/org/folio/rest/converter/assignedusers/AssignedUserCollectionItemConverter.java
src/main/java/org/folio/service/assignedusers/AssignedUsersServiceImpl.java
src/main/java/org/folio/service/users/UsersLookUpService.java
src/test/java/org/folio/service/assignedusers/AssignedUsersServiceImplTest.java
src/test/java/org/folio/service/users/UsersLookUpServiceTest.java

Sort assigned users by the last name
* sort users by last name after fetching from mod-users

MODKBEKBJ-662 Sort assigned users by last name

---

src/main/java/org/folio/service/users/UsersLookUpService.java

Fix not all assigned users retrieved at response
Update client service to set `limit` query  params equal to amount of IDs. The default limit for mod-users is 10.

MODKBEKBJ-665 Fix not all assigned users retrieved at response

---

src/main/java/org/folio/rest/impl/EholdingsResourcesImpl.java
src/main/java/org/folio/rmapi/ResourcesServiceImpl.java
src/test/java/org/folio/rest/impl/integrationsuite/EholdingsResourcesImplTest.java
src/test/resources/responses/rmapi/resources/get-resource-by-id-response-empty-customer-list.json

- check for empty customer resources
https://issues.folio.org/browse/MODKBEKBJ-688

MODKBEKBJ-688 IndexOutOfBoundException if resource customerResourcesList is empty

---

src/main/java/org/folio/service/holdings/HoldingsServiceImpl.java
src/test/java/org/folio/rest/impl/integrationsuite/DefaultLoadHoldingsImplTest.java
src/test/java/org/folio/util/HoldingsStatusUtil.java

https://issues.folio.org/browse/MODKBEKBJ-696

MODKBEKBJ-696 Load Holdings: NullPointerException while reading started date

---

NEWS.md
pom.xml

- Update RB to 35.0.0
- Update dependencies versions
- Update plugins versions
https://issues.folio.org/browse/MODKBEKBJ-692

MODKBEKBJ-692 RMB v35 upgrade

---

src/test/java/org/folio/rest/impl/integrationsuite/DefaultLoadHoldingsImplTest.java

As described in [MODKBEKBJ-575](https://issues.folio.org/browse/MODKBEKBJ-575), updating of holdings_status failed during load holdings but holdings were saved.
Presumably, it happens when snapshot creation failed, and then after the retry process, it was successful. Recovered with integration test to verify the assumption.
https://issues.folio.org/browse/MODKBEKBJ-575

MODKBEKBJ-575 - Load Holdings: Failed to update holdings_status

---

NEWS.md
pom.xml

Released v3.12.0 
Update NEWS.md

Release v3.12.0: Update NEWS and dependencies

---

src/main/java/org/folio/rest/util/ErrorHandler.java
src/main/java/org/folio/service/uc/UcCostPerUseServiceImpl.java
src/main/java/org/folio/service/uc/UcSettingsServiceImpl.java

Adding more logs for Usage Consolidation flow to make issues investigation easier.
Used Folie Logging approach.

MODKBEKBJ-726 Adding logs for Usage Consolidation flow

---

.github/workflows/api-doc.yml
.github/workflows/api-lint.yml
.github/workflows/api-schema-lint.yml
Jenkinsfile
README.md
ramls/eholdings.raml

[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
(instead of Jenkins-operated CI stages).

FOLIO-3678 MODKBEKBJ-742 Use GitHub Workflows api-lint and api-schema-lint and api-doc

---

NEWS.md
pom.xml
src/test/java/org/folio/rest/impl/integrationsuite/EholdingsAccessTypesImplTest.java
src/test/java/org/folio/rest/impl/integrationsuite/EholdingsAssignedUsersImplTest.java
src/test/java/org/folio/rest/impl/integrationsuite/EholdingsKbCredentialsImplTest.java

Prepare for next development iteration v4.2.0

Prepare for next development iteration v4.2.0

---

NEWS.md
pom.xml

https://folio-org.atlassian.net/browse/MODKBEKBJ-765
Remove unused commons-configuration2 dependency
Remove unused commons-configuration2 dependency
https://folio-org.atlassian.net/browse/MODKBEKBJ-765
Unused dependencies should be removed to reduce the jar size and to avoid work of the FOLIO security group.

MODKBEKBJ-765: Remove unused commons-configuration2 dependency

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

Review module descriptor
Permissions of the <span class="code" spellcheck="false">eholdings</span> interface changed. The endpoints require new permissions:
Method | Path | New permission
-- | -- | --
GET | /eholdings/kb-credentials/{credentialsId}/key | kb-ebsco.kb-credentials.key.item.get
GET | /eholdings/kb-credentials/{id}/uc/key | kb-ebsco.kb-credentials.uc.key.item.get
https://folio-org.atlassian.net/browse/MODKBEKBJ-769

build: update permissions for eholdings interface

---

NEWS.md
descriptors/ModuleDescriptor-template.json

Add missing module permissions to access-types endpoints
https://folio-org.atlassian.net/browse/MODKBEKBJ-770

fix: add missing module permissions to access-types endpoints

---

NEWS.md
pom.xml
src/main/java/org/folio/repository/holdings/HoldingsServiceMessagesFactory.java
src/main/java/org/folio/rest/converter/accesstypes/AccessTypeCollectionConverter.java
src/main/java/org/folio/rest/converter/accesstypes/AccessTypeConverter.java
src/main/java/org/folio/rest/converter/assignedusers/AssignedUserCollectionConverter.java
src/main/java/org/folio/rest/converter/costperuse/PackageCostPerUseConverter.java
src/main/java/org/folio/rest/converter/costperuse/ResourceCostPerUseCollectionConverter.java
src/main/java/org/folio/rest/converter/costperuse/ResourceCostPerUseConverter.java
src/main/java/org/folio/rest/converter/costperuse/TitleCostPerUseConverter.java
src/main/java/org/folio/rest/converter/currencies/CurrencyConverter.java
src/main/java/org/folio/rest/converter/kbcredentials/DbKbCredentialsConfigurationConverter.java
src/main/java/org/folio/rest/converter/kbcredentials/KbCredentialsCollectionConverter.java
src/main/java/org/folio/rest/converter/kbcredentials/KbCredentialsConverter.java
src/main/java/org/folio/rest/converter/labels/CustomLabelsCollectionConverter.java
src/main/java/org/folio/rest/converter/packages/PackageBulkFetchCollectionConverter.java
src/main/java/org/folio/rest/converter/providers/ProviderByIdConverter.java
src/main/java/org/folio/rest/converter/uc/UcSettingsConverter.java
src/main/java/org/folio/rest/converter/users/UserConverter.java
src/main/java/org/folio/rest/validator/CustomLabelsPutBodyValidator.java
src/main/java/org/folio/service/holdings/TransactionLoadServiceFacade.java
src/main/java/org/folio/service/holdings/message/MessageFactory.java
src/main/java/org/folio/service/locale/LocaleSettingsServiceImpl.java
src/main/java/org/folio/service/users/UsersLookUpService.java

Prepare for next development iteration v5.1.0

chore: prepare for next development iteration v5.1.0

---

NEWS.md
pom.xml
src/main/java/org/folio/repository/packages/PackageTableConstants.java

_Fix DB fetch query string for fetching packages with tags_
_Fix type_
[MODKBEKBJ-774](https://folio-org.atlassian.net/browse/MODKBEKBJ-774)

Release v4.1.1: MODKBEKBJ-774 - Fix DB query to fetch packages with tags

---

NEWS.md
src/main/java/org/folio/client/uc/UcApigeeEbscoClientImpl.java
src/main/java/org/folio/common/LogUtils.java
src/main/java/org/folio/repository/accesstypes/AccessTypeMappingsRepositoryImpl.java
src/main/java/org/folio/repository/accesstypes/AccessTypesRepositoryImpl.java
src/main/java/org/folio/repository/assigneduser/AssignedUserRepositoryImpl.java
src/main/java/org/folio/repository/currencies/CurrenciesRepositoryImpl.java
src/main/java/org/folio/repository/holdings/HoldingsRepositoryImpl.java
src/main/java/org/folio/repository/holdings/status/HoldingsStatusRepositoryImpl.java
src/main/java/org/folio/repository/holdings/status/audit/HoldingsStatusAuditRepositoryImpl.java
src/main/java/org/folio/repository/holdings/status/retry/RetryStatusRepositoryImpl.java
src/main/java/org/folio/repository/holdings/transaction/TransactionIdRepositoryImpl.java
src/main/java/org/folio/repository/kbcredentials/KbCredentialsRepositoryImpl.java
src/main/java/org/folio/repository/packages/PackageRepositoryImpl.java
src/main/java/org/folio/repository/providers/ProviderRepositoryImpl.java
src/main/java/org/folio/repository/resources/ResourceRepositoryImpl.java
src/main/java/org/folio/repository/tag/TagRepositoryImpl.java
src/main/java/org/folio/repository/titles/TitlesRepositoryImpl.java
src/main/java/org/folio/repository/uc/UcCredentialsRepositoryImpl.java
src/main/java/org/folio/repository/uc/UcSettingsRepositoryImpl.java
src/main/java/org/folio/service/uc/UcSettingsServiceImpl.java

Hide sensitive data in logs
adjust logging to hide sensitive data
https://folio-org.atlassian.net/browse/MODKBEKBJ-776

refactor: adjust logging to hide sensitive data
